In [11]:
import numpy as np
import pandas as pd

In [12]:
data = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/sfpd-dispatch/sfpd_dispatch_data_subset.csv');
data

,call_number,unit_id,incident_number,call_type,call_date,watch_date,received_timestamp,entry_timestamp,dispatch_timestamp,response_timestamp,...,number_of_alarms,unit_type,unit_sequence_in_call_dispatch,fire_prevention_district,supervisor_district,neighborhood_district,location,row_id,latitude,longitude
0,180243072,84,18010216,Medical Incident,2018-01-24,2018-01-24,2018-01-24 17:36:16.000000 UTC,2018-01-24 17:38:21.000000 UTC,2018-01-24 17:39:41.000000 UTC,2018-01-24 17:39:45.000000 UTC,...,1,MEDIC,1,7,1,NaN,"(37.77444199483868, -122.5046792231959)",180243072-84,37.774442,-122.504679
1,180240538,61,18010011,Medical Incident,2018-01-24,2018-01-23,2018-01-24 07:05:05.000000 UTC,2018-01-24 07:05:05.000000 UTC,2018-01-24 07:05:31.000000 UTC,2018-01-24 07:05:45.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.774094856688166, -122.42000143696421)",180240538-61,37.774095,-122.420001
2,180240176,E22,18009959,Medical Incident,2018-01-24,2018-01-23,2018-01-24 02:04:21.000000 UTC,2018-01-24 02:05:37.000000 UTC,2018-01-24 02:06:04.000000 UTC,2018-01-24 02:07:26.000000 UTC,...,1,ENGINE,1,8,7,NaN,"(37.75521795168784, -122.47554039050351)",180240176-E22,37.755218,-122.475540
3,180243588,E03,18010271,Alarms,2018-01-24,2018-01-24,2018-01-24 20:04:15.000000 UTC,2018-01-24 20:05:12.000000 UTC,2018-01-24 20:05:24.000000 UTC,2018-01-24 20:05:36.000000 UTC,...,1,ENGINE,1,4,2,NaN,"(37.79031930341935, -122.4231629067995)",180243588-E03,37.790319,-122.423163
4,180243590,B03,18010272,Alarms,2018-01-24,2018-01-24,2018-01-24 20:03:08.000000 UTC,2018-01-24 20:05:36.000000 UTC,2018-01-24 20:05:57.000000 UTC,2018-01-24 20:06:56.000000 UTC,...,1,CHIEF,3,3,6,NaN,"(37.77732776352611, -122.39308855968541)",180243590-B03,37.777328,-122.393089
5,180243782,E07,18010292,Alarms,2018-01-24,2018-01-24,2018-01-24 21:18:56.000000 UTC,2018-01-24 21:20:21.000000 UTC,2018-01-24 21:21:18.000000 UTC,2018-01-24 21:22:36.000000 UTC,...,1,ENGINE,1,6,8,NaN,"(37.756890170572206, -122.42222930549926)",180243782-E07,37.756890,-122.422229
6,180241852,E03,18010114,Structure Fire,2018-01-24,2018-01-24,2018-01-24 12:24:27.000000 UTC,2018-01-24 12:25:27.000000 UTC,2018-01-24 12:26:56.000000 UTC,2018-01-24 12:26:56.000000 UTC,...,1,ENGINE,8,2,6,NaN,"(37.783359002692066, -122.41669494404806)",180241852-E03,37.783359,-122.416695
7,180243546,66,18010265,Traffic Collision,2018-01-24,2018-01-24,2018-01-24 19:51:29.000000 UTC,2018-01-24 19:53:19.000000 UTC,2018-01-24 19:53:41.000000 UTC,2018-01-24 19:53:50.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.76924401107554, -122.40800720584919)",180243546-66,37.769244,-122.408007
8,180243952,E28,18010317,Alarms,2018-01-24,2018-01-24,2018-01-24 22:26:22.000000 UTC,2018-01-24 22:27:06.000000 UTC,2018-01-24 22:27:47.000000 UTC,2018-01-24 22:28:33.000000 UTC,...,1,ENGINE,1,1,3,NaN,"(37.80711992362169, -122.41642787206773)",180243952-E28,37.807120,-122.416428
9,180241350,58,18010067,Medical Incident,2018-01-24,2018-01-24,2018-01-24 10:35:00.000000 UTC,2018-01-24 10:36:55.000000 UTC,2018-01-24 10:37:06.000000 UTC,2018-01-24 10:37:09.000000 UTC,...,1,MEDIC,1,9,10,NaN,"(37.71214950882262, -122.41714122572772)",180241350-58,37.712150,-122.417141
10,180241957,53,18010125,Medical Incident,2018-01-24,2018-01-24,2018-01-24 12:53:39.000000 UTC,2018-01-24 12:53:39.000000 UTC,2018-01-24 12:55:17.000000 UTC,2018-01-24 12:55:28.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.77883231587925, -122.41564248785478)",180241957-53,37.778832,-122.415642
11,180242429,62,18010155,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:36:16.000000 UTC,2018-01-24 14:38:23.000000 UTC,2018-01-24 14:45:58.000000 UTC,2018-01-24 14:47:14.000000 UTC,...,1,MEDIC,1,1,3,NaN,"(37.79709205269086, -122.39833314918091)",180242429-62,37.797092,-122.398333
12,180243142,E11,18010223,Medical Incident,2018-01-24,2018-01-24,2018-01-24 17:56:16.000000 UTC,2018-01-24 17:58:32.000000 UTC,2018-01-24 17:59:52.000000 UTC,2018-01-24 18:00:50.000000 UTC,...,1,ENGINE,1,6,8,NaN,"(37.756096396025626, -122.42778335985659)",180243142-E11,37.756096,-122.427783
13,180242903,KM06,18010201,Medical Incident,2018-01-24,2018-01-24,2018-01-24 16:48:13.000000 UTC,2018-01-24 16:51:25.000000 UTC,2018-01-24 16:51:46.000000 UTC,2018-01-24 16:52:30.000000 UTC,...,1,PRIVATE,2,3,6,NaN,"(37.78079208027532, -122.40838574549893)",180242903-KM06,37.780792,-122.408386
14,180243517,85,18010262,Medical Incident,2018-01-24,2018-01-24,2018-01-24 19:41:44.000000 UTC,2018-01-24 19:44:22.000000 UTC,2018-01-24 19:45:15.000000 UTC,2018-01-24 19:45:21.000000 UTC,...,1,MEDIC,2,6,9,NaN,"(37.75223945497915, -122.41844527285122)",180243517-85,37.752239,-122.418445
15,180240052,RS1,18009942,Structure Fire,2018-01-24,2018-01-23,2018-01-24 00:19:30.000000 UTC,2018-01-24 00:34:51.000000 UTC,2018-01-24 00:35:09.000000 UTC,2018-01-24 00:36:32.000000 UTC,...,1,RESCUE SQUAD,6,2,6,NaN,"(37.78521736163072, -122.41706961139498)",180240052-RS1,37.785217,-122.417070
16,180241776,E03,18010110,Medical Incident,2018-01-24,2018-01-24,2018-01-24 12:08:29.000000 UTC,2018-01-24 12:10:03.000000 UTC,2018-01-24 12:10:43.000000 UTC,2018-01-24 12:11:43.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.77952317116152, -122.41263929179321)",180241776-E03,37.779523,-122.412639
17,180242487,E20,18010161,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:54:21.000000 UTC,2018-01-24 14:57:25.000000 UTC,2018-01-24 15:01:11.000000 UTC,2018-01-24 15:02:25.000000 UTC,...,1,ENGINE,1,8,7,NaN,"(37.74817254773626, -122.45869503396155)",180242487-E20,37.748173,-122.458695
18,180243850,72,18010301,Medical Incident,2018-01-24,2018-01-24,2018-01-24 21:42:22.000000 UTC,2018-01-24 21:46:48.000000 UTC,2018-01-24 21:47:16.000000 UTC,2018-01-24 21:47:21.000000 UTC,...,1,MEDIC,1,5,5,NaN,"(37.770054661455546, -122.44612843129843)",180243850-72,37.770055,-122.446128
19,180241852,T01,18010114,Structure Fire,2018-01-24,2018-01-24,2018-01-24 12:24:27.000000 UTC,2018-01-24 12:25:27.000000 UTC,2018-01-24 12:25:47.000000 UTC,2018-01-24 12:25:53.000000 UTC,...,1,TRUCK,10,2,6,NaN,"(37.783359002692066, -122.41669494404806)",180241852-T01,37.783359,-122.416695
20,180242322,64,18010144,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:10:45.000000 UTC,2018-01-24 14:11:48.000000 UTC,2018-01-24 14:12:10.000000 UTC,2018-01-24 14:12:16.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.77779030942458, -122.41283433212864)",180242322-64,37.777790,-122.412834
21,180241372,E01,18010072,Medical Incident,2018-01-24,2018-01-24,2018-01-24 10:40:14.000000 UTC,2018-01-24 10:41:06.000000 UTC,2018-01-24 10:41:22.000000 UTC,2018-01-24 10:42:30.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.78066916324976, -122.40167804559798)",180241372-E01,37.780669,-122.401678
22,180241696,E21,18010100,Medical Incident,2018-01-24,2018-01-24,2018-01-24 11:52:30.000000 UTC,2018-01-24 11:52:43.000000 UTC,2018-01-24 11:52:59.000000 UTC,2018-01-24 11:54:59.000000 UTC,...,1,ENGINE,1,5,5,NaN,"(37.774092678704704, -122.44108442596955)",180241696-E21,37.774093,-122.441084
23,180242478,E28,18010160,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:51:27.000000 UTC,2018-01-24 14:54:11.000000 UTC,2018-01-24 15:01:45.000000 UTC,2018-01-24 15:02:44.000000 UTC,...,1,ENGINE,1,1,3,NaN,"(37.80282769816514, -122.41303433677871)",180242478-E28,37.802828,-122.413034
24,180240880,79,18010040,Medical Incident,2018-01-24,2018-01-24,2018-01-24 08:50:47.000000 UTC,2018-01-24 08:52:11.000000 UTC,2018-01-24 08:52:29.000000 UTC,2018-01-24 08:52:36.000000 UTC,...,1,MEDIC,1,1,6,NaN,"(37.78626844171618, -122.41299723589641)",180240880-79,37.786268,-122.412997
25,180242627,52,18010178,Medical Incident,2018-01-24,2018-01-24,2018-01-24 15:31:54.000000 UTC,2018-01-24 15:32:57.000000 UTC,2018-01-24 15:33:39.000000 UTC,2018-01-24 15:34:32.000000 UTC,...,1,MEDIC,2,5,5,NaN,"(37.770273091358646, -122.4486050480563)",180242627-52,37.770273,-122.448605
26,180242103,52,18010133,Medical Incident,2018-01-24,2018-01-24,2018-01-24 13:19:28.000000 UTC,2018-01-24 13:21:23.000000 UTC,2018-01-24 13:22:11.000000 UTC,2018-01-24 13:22:20.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.78191397441793, -122.41303219395635)",180242103-52,37.781914,-122.413032
27,180243393,71,18010251,Other,2018-01-24,2018-01-24,2018-01-24 19:07:16.000000 UTC,2018-01-24 19:07:16.000000 UTC,2018-01-24 21:45:14.000000 UTC,2018-01-24 21:45:14.000000 UTC,...,1,MEDIC,2,9,9,NaN,"(37.72229807127346, -122.41130309997389)",180243393-71,37.722298,-122.411303
28,180240248,94,18009965,Medical Incident,2018-01-24,2018-01-23,2018-01-24 03:14:26.000000 UTC,2018-01-24 03:16:33.000000 UTC,2018-01-24 03:16:45.000000 UTC,2018-01-24 03:17:12.000000 UTC,...,1,MEDIC,1,6,9,NaN,"(37.75962769270459, -122.41592301840338)",180240248-94,37.759628,-122.415923
29,180241729,E36,18010106,Medical Incident,2018-01-24,2018-01-24,2018-01-24 11:59:40.000000 UTC,2018-01-24 12:00:40.000000 UTC,2018-01-24 12:01:55.000000 UTC,2018-01-24 12:01:55.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.78186544733037, -122.41428534642068)",180241729-E36,37.781865,-122.414285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,180132359,E05,18005688,Medical Incident,2018-01-13,2018-01-13,2018-01-13 15:51:50.000000 UTC,2018-01-13 15:52:14.000000 UTC,2018-01-13 15:52:34.000000 UTC,2018-01-13 15:53:24.000000 UTC,...,1,ENGINE,2,5,8,NaN,"(37.76177683437902, -122.43515167277485)",180132359-E05,37.761777,-122.435152
9971,180130474,E40,18005495,Medical Incident,2018-01-13,2018-01-12,2018-01-13 04:07:51.000000 UTC,2018-01-13 04:07:51.000000 UTC,2018-01-13 04:08:19.000000 UTC,2018-01-13 04:09:43.000000 UTC,...,1,ENGINE,1,8,4,NaN,"(37.74201996298055, -122.47783880287392)",180130474-E40,37.742020,-122.477839
9972,180131955,53,18005645,Traffic Collision,2018-01-13,2018-01-13,2018-01-13 13:57:05.000000 UTC,2018-01-13 14:00:06.000000 UTC,2018-01-13 14:13:58.000000 UTC,2018-01-13 14:13:58.000000 UTC,...,1,MEDIC,3,10,9,NaN,"(37.731819888971835, -122.40541209173365)",180131955-53,37.731820,-122.405412
9973,180133046,T03,18005746,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:34:20.000000 UTC,2018-01-13 18:36:16.000000 UTC,2018-01-13 18:37:45.000000 UTC,2018-01-13 18:40:06.000000 UTC,...,1,TRUCK,3,2,6,NaN,"(37.78244403834035, -122.42057454560377)",180133046-T03,37.782444,-122.420575
9974,180130990,RC4,18005555,Medical Incident,2018-01-13,2018-01-13,2018-01-13 09:24:39.000000 UTC,2018-01-13 09:25:14.000000 UTC,2018-01-13 09:27:07.000000 UTC,2018-01-13 09:27:07.000000 UTC,...,1,RESCUE CAPTAIN,1,9,11,NaN,"(37.720457745745186, -122.43703098791046)",180130990-RC4,37.720458,-122.437031
9975,180131726,AM106,18005622,Medical Incident,2018-01-13,2018-01-13,2018-01-13 13:03:23.000000 UTC,2018-01-13 13:04:34.000000 UTC,2018-01-13 13:05:17.000000 UTC,2018-01-13 13:06:12.000000 UTC,...,1,PRIVATE,2,3,6,NaN,"(37.783310406701474, -122.3883798739193)",180131726-AM106,37.783310,-122.388380
9976,180131196,E08,18005577,Medical Incident,2018-01-13,2018-01-13,2018-01-13 10:28:41.000000 UTC,2018-01-13 10:30:14.000000 UTC,2018-01-13 10:30:30.000000 UTC,2018-01-13 10:32:13.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.7748701729732, -122.39441707175159)",180131196-E08,37.774870,-122.394417
9977,180130840,KM08,18005547,Medical Incident,2018-01-13,2018-01-13,2018-01-13 08:28:10.000000 UTC,2018-01-13 08:29:45.000000 UTC,2018-01-13 08:29:58.000000 UTC,2018-01-13 08:30:25.000000 UTC,...,1,PRIVATE,1,1,3,NaN,"(37.80480917127099, -122.4067955298258)",180130840-KM08,37.804809,-122.406796
9978,180131435,E17,18005600,Medical Incident,2018-01-13,2018-01-13,2018-01-13 11:37:39.000000 UTC,2018-01-13 11:38:15.000000 UTC,2018-01-13 11:39:17.000000 UTC,2018-01-13 11:40:33.000000 UTC,...,1,ENGINE,1,10,10,NaN,"(37.71986847521028, -122.39090480126804)",180131435-E17,37.719868,-122.390905
9979,180133469,E21,18005793,Medical Incident,2018-01-13,2018-01-13,2018-01-13 20:33:54.000000 UTC,2018-01-13 20:34:44.000000 UTC,2018-01-13 20:35:08.000000 UTC,2018-01-13 20:36:18.000000 UTC,...,1,ENGINE,1,5,5,NaN,"(37.78116830793363, -122.43480568645582)",180133469-E21,37.781168,-122.434806
9980,180130642,E36,18005530,Structure Fire,2018-01-13,2018-01-12,2018-01-13 06:45:11.000000 UTC,2018-01-13 06:47:35.000000 UTC,2018-01-13 06:47:48.000000 UTC,2018-01-13 06:49:05.000000 UTC,...,1,ENGINE,3,2,9,NaN,"(37.76613438751412, -122.4219350771774)",180130642-E36,37.766134,-122.421935
9981,180133046,65,18005746,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:34:20.000000 UTC,2018-01-13 18:36:16.000000 UTC,2018-01-13 18:37:45.000000 UTC,2018-01-13 18:40:39.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.78244403834035, -122.42057454560377)",180133046-65,37.782444,-122.420575
9982,180130372,AM118,18005479,Traffic Collision,2018-01-13,2018-01-12,2018-01-13 02:52:48.000000 UTC,2018-01-13 02:56:15.000000 UTC,2018-01-13 02:57:03.000000 UTC,2018-01-13 02:58:02.000000 UTC,...,1,PRIVATE,1,None,6,NaN,"(37.810520722520614, -122.36513827228869)",180130372-AM118,37.810521,-122.365138
9983,180131982,KM01,18005647,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:07:21.000000 UTC,2018-01-13 14:07:21.000000 UTC,2018-01-13 14:07:46.000000 UTC,2018-01-13 14:08:18.000000 UTC,...,1,PRIVATE,2,4,2,NaN,"(37.797298027689145, -122.43384673464273)",180131982-KM01,37.797298,-122.433847
9984,180133500,73,18005798,Medical Incident,2018-01-13,2018-01-13,2018-01-13 20:46:37.000000 UTC,2018-01-13 20:46:37.000000 UTC,2018-01-13 20:47:10.000000 UTC,2018-01-13 20:47:18.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.77609673484532, -122.4085642977398)",180133500-73,37.776097,-122.408564
9985,180133012,RC3,18005736,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:29:44.000000 UTC,2018-01-13 18:31:35.000000 UTC,2018-01-13 18:34:37.000000 UTC,2018-01-13 18:34:37.000000 UTC,...,1,RESCUE CAPTAIN,2,10,10,NaN,"(37.7501183410943, -122.39043303882671)",180133012-RC3,37.750118,-122.390433
9986,180132009,E06,18005652,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:14:17.000000 UTC,2018-01-13 14:15:19.000000 UTC,2018-01-13 14:17:00.000000 UTC,2018-01-13 14:18:06.000000 UTC,...,1,ENGINE,3,6,8,NaN,"(37.76063768316806, -122.42584369698614)",180132009-E06,37.760638,-122.425844
9987,180130712,E31,18005537,Medical Incident,2018-01-13,2018-01-12,2018-01-13 07:28:39.000000 UTC,2018-01-13 07:29:26.000000 UTC,2018-01-13 07:29:51.000000 UTC,2018-01-13 07:30:29.000000 UTC,...,1,ENGINE,2,7,1,NaN,"(37.77995613136864, -122.4664265905931)",180130712-E31,37.779956,-122.466427
9988,180131651,95,18005616,Medical Incident,2018-01-13,2018-01-13,2018-01-13 12:41:29.000000 UTC,2018-01-13 12:41:29.000000 UTC,2018-01-13 12:41:41.000000 UTC,2018-01-13 12:41:59.000000 UTC,...,1,MEDIC,1,5,5,NaN,"(37.76815416294501, -122.45431162017093)",180131651-95,37.768154,-122.454312
9989,180131331,60,18005589,Medical Incident,2018-01-13,2018-01-13,2018-01-13 11:09:14.000000 UTC,2018-01-13 11:10:03.000000 UTC,2018-01-13 11:10:26.000000 UTC,2018-01-13 11:10:44.000000 UTC,...,1,MEDIC,2,1,3,NaN,"(37.791834627188145, -122.41081753529559)",180131331-60,37.791835,-122.410818
9990,180130697,E06,18005536,Other,2018-01-13,2018-01-12,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,...,1,ENGINE,1,5,8,NaN,"(37.767191551371724, -122.43122179729654)",180130697-E06,37.767192,-122.431222
9991,180130354,70,18005475,Medical Incident,2018-01-13,2018-01-12,2018-01-13 02:44:30.000000 UTC,2018-01-13 02:46:08.000000 UTC,2018-01-13 02:47:17.000000 UTC,2018-01-13 02:47:23.000000 UTC,...,1,MEDIC,1,2,5,NaN,"(37.77588508583154, -122.43036534649241)",180130354-70,37.775885,-122.430365
9992,180134026,E01,18005845,Traffic Collision,2018-01-13,2018-01-13,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.77128552595309, -122.41320426710206)",180134026-E01,37.771286,-122.413204
9993,180132041,58,18005657,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:23:06.000000 UTC,2018-01-13 14:23:59.000000 UTC,2018-01-13 14:24:23.000000 UTC,2018-01-13 14:24:30.000000 UTC,...,1,MEDIC,1,2,8,NaN,"(37.761513913312704, -122.42555596887412)",180132041-58,37.761514,-122.425556
9994,180133993,E18,18005843,Medical Incident,2018-01-13,2018-01-13,2018-01-13 23:26:46.000000 UTC,2018-01-13 23:27:44.000000 UTC,2018-01-13 23:28:24.000000 UTC,2018-01-13 23:30:17.000000 UTC,...,1,ENGINE,1,8,4,NaN,"(37.74910205932908, -122.48692720556181)",180133993-E18,37.749102,-122.486927
9995,180130129,E07,18005442,Medical Incident,2018-01-13,2018-01-12,2018-01-13 00:48:33.000000 UTC,2018-01-13 00:48:33.000000 UTC,2018-01-13 00:49:23.000000 UTC,2018-01-13 00:49:42.000000 UTC,...,1,ENGINE,2,6,9,NaN,"(37.75796959799367, -122.41672705336742)",180130129-E07,37.757970,-122.416727
9996,180130999,E38,18005556,Medical Incident,2018-01-13,2018-01-13,2018-01-13 09:26:55.000000 UTC,2018-01-13 09:27:33.000000 UTC,2018-01-13 09:27:50.000000 UTC,2018-01-13 09:29:36.000000 UTC,...,1,ENGINE,1,4,5,NaN,"(37.78708178866631, -122.4258678201407)",180130999-E38,37.787082,-122.425868
9997,180131985,E03,18005648,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:09:05.000000 UTC,2018-01-13 14:10:04.000000 UTC,2018-01-13 14:12:37.000000 UTC,2018-01-13 14:14:08.000000 UTC,...,1,ENGINE,3,3,6,NaN,"(37.784205674933816, -122.40761273180911)",180131985-E03,37.784206,-122.407613
9998,180132432,RWC2,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:16:14.000000 UTC,...,1,SUPPORT,9,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-RWC2,37.805163,-122.432957
9999,180131803,82,18005629,Medical Incident,2018-01-13,2018-01-13,2018-01-13 13:17:25.000000 UTC,2018-01-13 13:20:29.000000 UTC,2018-01-13 13:20:47.000000 UTC,2018-01-13 13:21:07.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.78558247360873, -122.41461720883616)",180131803-82,37.785582,-122.414617

In [13]:
dataFrame = data.sort_values('unit_type');
dataFrame

,call_number,unit_id,incident_number,call_type,call_date,watch_date,received_timestamp,entry_timestamp,dispatch_timestamp,response_timestamp,...,number_of_alarms,unit_type,unit_sequence_in_call_dispatch,fire_prevention_district,supervisor_district,neighborhood_district,location,row_id,latitude,longitude
1314,180233454,B05,18009860,Alarms,2018-01-23,2018-01-23,2018-01-23 19:18:01.000000 UTC,2018-01-23 19:21:40.000000 UTC,2018-01-23 19:21:45.000000 UTC,2018-01-23 19:23:06.000000 UTC,...,1,CHIEF,3,5,8,NaN,"(37.760410698540674, -122.4463434724725)",180233454-B05,37.760411,-122.446343
857,180231714,B10,18009698,Gas Leak (Natural and LP Gases),2018-01-23,2018-01-23,2018-01-23 12:23:59.000000 UTC,2018-01-23 12:26:06.000000 UTC,2018-01-23 12:27:02.000000 UTC,2018-01-23 12:27:34.000000 UTC,...,1,CHIEF,2,10,10,NaN,"(37.73727088832427, -122.39826366470116)",180231714-B10,37.737271,-122.398264
8500,180140506,D3,18005912,Train / Rail Incident,2018-01-14,2018-01-13,2018-01-14 04:39:51.000000 UTC,2018-01-14 05:00:06.000000 UTC,2018-01-14 05:02:17.000000 UTC,2018-01-14 05:04:46.000000 UTC,...,1,CHIEF,13,1,3,NaN,"(37.79282365093117, -122.39703419008931)",180140506-D3,37.792824,-122.397034
4623,180194207,B05,18008309,Medical Incident,2018-01-19,2018-01-19,2018-01-19 23:15:08.000000 UTC,2018-01-19 23:15:58.000000 UTC,2018-01-19 23:16:47.000000 UTC,2018-01-19 23:18:12.000000 UTC,...,1,CHIEF,5,5,5,NaN,"(37.780026750015004, -122.4362591774677)",180194207-B05,37.780027,-122.436259
7437,180162547,B04,18006958,Gas Leak (Natural and LP Gases),2018-01-16,2018-01-16,2018-01-16 14:53:26.000000 UTC,2018-01-16 14:55:19.000000 UTC,2018-01-16 14:56:15.000000 UTC,2018-01-16 14:57:25.000000 UTC,...,1,CHIEF,2,4,2,NaN,"(37.798062779647125, -122.42405842443445)",180162547-B04,37.798063,-122.424058
6455,180174110,B02,18007481,Alarms,2018-01-17,2018-01-17,2018-01-17 22:06:53.000000 UTC,2018-01-17 22:08:59.000000 UTC,2018-01-17 22:10:55.000000 UTC,2018-01-17 22:11:04.000000 UTC,...,1,CHIEF,1,2,6,NaN,"(37.7806168446664, -122.41656225429274)",180174110-B02,37.780617,-122.416562
7434,180163801,B01,18007061,Alarms,2018-01-16,2018-01-16,2018-01-16 19:52:53.000000 UTC,2018-01-16 19:54:01.000000 UTC,2018-01-16 19:54:51.000000 UTC,2018-01-16 19:55:00.000000 UTC,...,1,CHIEF,2,1,3,NaN,"(37.79838395974508, -122.41835547749263)",180163801-B01,37.798384,-122.418355
8509,180140190,B06,18005867,Other,2018-01-14,2018-01-13,2018-01-14 01:17:54.000000 UTC,2018-01-14 01:17:54.000000 UTC,2018-01-14 01:21:01.000000 UTC,2018-01-14 01:23:29.000000 UTC,...,1,CHIEF,1,6,9,NaN,"(37.756363300116085, -122.41671210080577)",180140190-B06,37.756363,-122.416712
6463,180173455,EMS6,18007412,Medical Incident,2018-01-17,2018-01-17,2018-01-17 18:29:16.000000 UTC,2018-01-17 18:31:54.000000 UTC,2018-01-17 18:33:55.000000 UTC,2018-01-17 18:36:42.000000 UTC,...,1,CHIEF,3,1,3,NaN,"(37.793256349048015, -122.39630200430632)",180173455-EMS6,37.793256,-122.396302
4610,180192091,B01,18008109,Alarms,2018-01-19,2018-01-19,2018-01-19 14:17:10.000000 UTC,2018-01-19 14:19:46.000000 UTC,2018-01-19 14:19:56.000000 UTC,NaN,...,1,CHIEF,3,1,3,NaN,"(37.804438297245156, -122.41160547614237)",180192091-B01,37.804438,-122.411605
1970,180222922,B02,18009411,Alarms,2018-01-22,2018-01-22,2018-01-22 17:39:23.000000 UTC,2018-01-22 17:41:16.000000 UTC,2018-01-22 17:41:24.000000 UTC,2018-01-22 17:43:39.000000 UTC,...,1,CHIEF,3,3,6,NaN,"(37.78347684038751, -122.4124351407277)",180222922-B02,37.783477,-122.412435
1965,180220801,D2,18009207,Structure Fire,2018-01-22,2018-01-22,2018-01-22 08:53:25.000000 UTC,2018-01-22 08:53:36.000000 UTC,2018-01-22 08:53:51.000000 UTC,2018-01-22 08:55:49.000000 UTC,...,1,CHIEF,9,4,3,NaN,"(37.79102834173834, -122.4208486210382)",180220801-D2,37.791028,-122.420849
7423,180163460,B08,18007027,Alarms,2018-01-16,2018-01-16,2018-01-16 18:17:58.000000 UTC,2018-01-16 18:19:28.000000 UTC,2018-01-16 18:19:34.000000 UTC,2018-01-16 18:21:29.000000 UTC,...,1,CHIEF,2,8,7,NaN,"(37.7459562953856, -122.45423990761294)",180163460-B08,37.745956,-122.454240
8515,180141576,B10,18006026,Gas Leak (Natural and LP Gases),2018-01-14,2018-01-14,2018-01-14 12:39:19.000000 UTC,2018-01-14 12:42:08.000000 UTC,2018-01-14 12:42:39.000000 UTC,2018-01-14 12:43:59.000000 UTC,...,1,CHIEF,2,10,10,NaN,"(37.73641225333125, -122.38291964632427)",180141576-B10,37.736412,-122.382920
6475,180170242,D3,18007147,Structure Fire,2018-01-17,2018-01-16,2018-01-17 02:29:53.000000 UTC,2018-01-17 02:31:02.000000 UTC,2018-01-17 02:31:19.000000 UTC,2018-01-17 02:33:28.000000 UTC,...,1,CHIEF,6,9,7,NaN,"(37.72989603655827, -122.4561633416235)",180170242-D3,37.729896,-122.456163
4592,180192705,B08,18008167,Medical Incident,2018-01-19,2018-01-19,2018-01-19 16:39:54.000000 UTC,2018-01-19 16:39:54.000000 UTC,2018-01-19 16:40:30.000000 UTC,2018-01-19 16:42:14.000000 UTC,...,1,CHIEF,3,8,4,NaN,"(37.752600056170664, -122.49241358966208)",180192705-B08,37.752600,-122.492414
4588,180193480,B08,18008219,Alarms,2018-01-19,2018-01-19,2018-01-19 19:32:23.000000 UTC,2018-01-19 19:33:47.000000 UTC,2018-01-19 19:33:53.000000 UTC,2018-01-19 19:34:18.000000 UTC,...,1,CHIEF,3,8,7,NaN,"(37.730313216900235, -122.48620543825633)",180193480-B08,37.730313,-122.486205
891,180230213,D3,18009566,Structure Fire,2018-01-23,2018-01-22,2018-01-23 02:40:59.000000 UTC,2018-01-23 02:42:18.000000 UTC,2018-01-23 02:47:05.000000 UTC,2018-01-23 02:48:10.000000 UTC,...,1,CHIEF,9,9,11,NaN,"(37.711379707354034, -122.45034108438057)",180230213-D3,37.711380,-122.450341
9316,180130930,B09,18005554,Structure Fire,2018-01-13,2018-01-13,2018-01-13 09:06:03.000000 UTC,2018-01-13 09:07:54.000000 UTC,2018-01-13 09:08:09.000000 UTC,2018-01-13 09:09:29.000000 UTC,...,1,CHIEF,5,9,7,NaN,"(37.733117547930775, -122.4576410029956)",180130930-B09,37.733118,-122.457641
6483,180171946,B01,18007296,Outside Fire,2018-01-17,2018-01-17,2018-01-17 12:38:42.000000 UTC,2018-01-17 12:38:42.000000 UTC,2018-01-17 12:39:06.000000 UTC,2018-01-17 12:40:32.000000 UTC,...,1,CHIEF,3,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180171946-B01,37.798045,-122.396367
3383,180201966,B08,18008538,Alarms,2018-01-20,2018-01-20,2018-01-20 14:07:09.000000 UTC,2018-01-20 14:08:13.000000 UTC,2018-01-20 14:08:34.000000 UTC,2018-01-20 14:09:57.000000 UTC,...,1,CHIEF,2,8,4,NaN,"(37.7570337296554, -122.4767584370093)",180201966-B08,37.757034,-122.476758
1952,180223919,B08,18009516,Alarms,2018-01-22,2018-01-22,2018-01-22 22:21:24.000000 UTC,2018-01-22 22:23:31.000000 UTC,2018-01-22 22:23:57.000000 UTC,2018-01-22 22:24:42.000000 UTC,...,1,CHIEF,3,8,7,NaN,"(37.71433481369802, -122.49204787167777)",180223919-B08,37.714335,-122.492048
6488,180174151,B04,18007483,Gas Leak (Natural and LP Gases),2018-01-17,2018-01-17,2018-01-17 22:25:01.000000 UTC,2018-01-17 22:26:36.000000 UTC,2018-01-17 22:26:53.000000 UTC,2018-01-17 22:28:14.000000 UTC,...,1,CHIEF,2,4,2,NaN,"(37.799004026765914, -122.44179524120398)",180174151-B04,37.799004,-122.441795
8523,180141672,B02,18006039,Alarms,2018-01-14,2018-01-14,2018-01-14 13:11:36.000000 UTC,2018-01-14 13:12:53.000000 UTC,2018-01-14 13:13:53.000000 UTC,2018-01-14 13:16:08.000000 UTC,...,1,CHIEF,3,3,6,NaN,"(37.785736787880914, -122.38912436441233)",180141672-B02,37.785737,-122.389124
6491,180173523,B02,18007419,Traffic Collision,2018-01-17,2018-01-17,2018-01-17 18:50:34.000000 UTC,2018-01-17 18:50:34.000000 UTC,2018-01-17 18:51:41.000000 UTC,2018-01-17 18:54:05.000000 UTC,...,1,CHIEF,2,2,5,NaN,"(37.777972264371485, -122.42235388881045)",180173523-B02,37.777972,-122.422354
9304,180132858,B01,18005722,Structure Fire,2018-01-13,2018-01-13,2018-01-13 17:53:30.000000 UTC,2018-01-13 17:53:58.000000 UTC,2018-01-13 17:54:12.000000 UTC,2018-01-13 17:55:03.000000 UTC,...,1,CHIEF,4,1,6,NaN,"(37.78626844171618, -122.41299723589641)",180132858-B01,37.786268,-122.412997
3392,180200417,B01,18008371,Alarms,2018-01-20,2018-01-19,2018-01-20 03:59:25.000000 UTC,2018-01-20 04:00:40.000000 UTC,2018-01-20 04:01:31.000000 UTC,2018-01-20 04:03:47.000000 UTC,...,1,CHIEF,2,1,3,NaN,"(37.78706546639106, -122.41315981666592)",180200417-B01,37.787065,-122.413160
1946,180220449,B07,18009172,Alarms,2018-01-22,2018-01-21,2018-01-22 06:31:22.000000 UTC,2018-01-22 06:33:51.000000 UTC,2018-01-22 06:34:07.000000 UTC,2018-01-22 06:36:25.000000 UTC,...,1,CHIEF,2,3,6,NaN,"(37.779167421925955, -122.40634642563238)",180220449-B07,37.779167,-122.406346
4629,180193048,B01,18008186,Alarms,2018-01-19,2018-01-19,2018-01-19 17:47:08.000000 UTC,2018-01-19 17:49:45.000000 UTC,2018-01-19 17:49:56.000000 UTC,2018-01-19 17:51:31.000000 UTC,...,1,CHIEF,1,1,3,NaN,"(37.79456754207132, -122.40745780854365)",180193048-B01,37.794568,-122.407458
3393,180202662,B04,18008614,Structure Fire,2018-01-20,2018-01-20,2018-01-20 17:26:24.000000 UTC,2018-01-20 17:26:24.000000 UTC,2018-01-20 17:26:34.000000 UTC,2018-01-20 17:28:13.000000 UTC,...,1,CHIEF,3,4,5,NaN,"(37.785061737121815, -122.42643012772973)",180202662-B04,37.785062,-122.426430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8363,180150897,T06,18006374,Structure Fire,2018-01-15,2018-01-15,2018-01-15 09:14:37.000000 UTC,2018-01-15 09:14:37.000000 UTC,2018-01-15 09:15:08.000000 UTC,2018-01-15 09:15:52.000000 UTC,...,1,TRUCK,1,2,9,NaN,"(37.76959270625443, -122.41668848587886)",180150897-T06,37.769593,-122.416688
2183,180223480,T03,18009467,Structure Fire,2018-01-22,2018-01-22,2018-01-22 20:03:34.000000 UTC,2018-01-22 20:03:34.000000 UTC,2018-01-22 20:03:45.000000 UTC,2018-01-22 20:07:09.000000 UTC,...,1,TRUCK,2,1,3,NaN,"(37.786409613771546, -122.4080362362708)",180223480-T03,37.786410,-122.408036
6307,180171595,T11,18007259,Citizen Assist / Service Call,2018-01-17,2018-01-17,2018-01-17 11:07:35.000000 UTC,2018-01-17 11:09:00.000000 UTC,2018-01-17 11:09:09.000000 UTC,2018-01-17 11:10:55.000000 UTC,...,1,TRUCK,1,6,8,NaN,"(37.74810004173221, -122.42701514580305)",180171595-T11,37.748100,-122.427015
2185,180223077,T01,18009427,Structure Fire,2018-01-22,2018-01-22,2018-01-22 18:16:13.000000 UTC,2018-01-22 18:16:13.000000 UTC,2018-01-22 18:16:17.000000 UTC,2018-01-22 18:17:47.000000 UTC,...,1,TRUCK,2,3,6,NaN,"(37.77903213273744, -122.40184327443923)",180223077-T01,37.779032,-122.401843
4839,180193809,T11,18008267,Alarms,2018-01-19,2018-01-19,2018-01-19 21:07:36.000000 UTC,2018-01-19 21:09:22.000000 UTC,2018-01-19 21:09:38.000000 UTC,2018-01-19 21:11:10.000000 UTC,...,1,TRUCK,2,6,8,NaN,"(37.74951187279234, -122.42368456023766)",180193809-T11,37.749512,-122.423685
5961,180173327,T16,18007401,Alarms,2018-01-17,2018-01-17,2018-01-17 18:01:59.000000 UTC,2018-01-17 18:04:22.000000 UTC,2018-01-17 18:04:26.000000 UTC,2018-01-17 18:06:15.000000 UTC,...,1,TRUCK,3,7,1,NaN,"(37.77671905079736, -122.4586117219497)",180173327-T16,37.776719,-122.458612
8426,180140570,T12,18005922,Structure Fire,2018-01-14,2018-01-13,2018-01-14 06:08:56.000000 UTC,2018-01-14 06:12:08.000000 UTC,2018-01-14 06:12:40.000000 UTC,2018-01-14 06:14:27.000000 UTC,...,1,TRUCK,9,7,5,NaN,"(37.764836265712674, -122.46965698795425)",180140570-T12,37.764836,-122.469657
8443,180140508,T04,18005913,Alarms,2018-01-14,2018-01-13,2018-01-14 05:03:00.000000 UTC,2018-01-14 05:05:09.000000 UTC,2018-01-14 05:05:16.000000 UTC,2018-01-14 05:07:16.000000 UTC,...,1,TRUCK,2,3,10,NaN,"(37.76362722874533, -122.38972338997317)",180140508-T04,37.763627,-122.389723
8508,180143391,T05,18006207,Elevator / Escalator Rescue,2018-01-14,2018-01-14,2018-01-14 21:27:21.000000 UTC,2018-01-14 21:28:46.000000 UTC,2018-01-14 21:29:04.000000 UTC,2018-01-14 21:30:06.000000 UTC,...,1,TRUCK,1,5,5,NaN,"(37.7826256736324, -122.43418775505465)",180143391-T05,37.782626,-122.434188
1977,180223847,T16,18009508,Gas Leak (Natural and LP Gases),2018-01-22,2018-01-22,2018-01-22 22:01:49.000000 UTC,2018-01-22 22:02:58.000000 UTC,2018-01-22 22:03:13.000000 UTC,2018-01-22 22:05:01.000000 UTC,...,1,TRUCK,2,5,5,NaN,"(37.77336601296033, -122.45013888651042)",180223847-T16,37.773366,-122.450139
8502,180142223,T01,18006089,Elevator / Escalator Rescue,2018-01-14,2018-01-14,2018-01-14 16:02:04.000000 UTC,2018-01-14 16:03:33.000000 UTC,2018-01-14 16:03:41.000000 UTC,2018-01-14 16:04:23.000000 UTC,...,1,TRUCK,1,2,6,NaN,"(37.77649448087791, -122.41135913835731)",180142223-T01,37.776494,-122.411359
4883,180194158,T09,18008306,Citizen Assist / Service Call,2018-01-19,2018-01-19,2018-01-19 22:53:56.000000 UTC,2018-01-19 22:55:56.000000 UTC,2018-01-19 22:56:02.000000 UTC,2018-01-19 22:57:57.000000 UTC,...,1,TRUCK,2,10,10,NaN,"(37.75633027490241, -122.39556536014139)",180194158-T09,37.756330,-122.395565
4882,180193424,T14,18008213,Structure Fire,2018-01-19,2018-01-19,2018-01-19 19:15:11.000000 UTC,2018-01-19 19:16:36.000000 UTC,2018-01-19 19:17:11.000000 UTC,2018-01-19 19:18:11.000000 UTC,...,1,TRUCK,1,8,4,NaN,"(37.76374916070977, -122.49426738312347)",180193424-T14,37.763749,-122.494267
8491,180142739,T06,18006137,Elevator / Escalator Rescue,2018-01-14,2018-01-14,2018-01-14 18:00:19.000000 UTC,2018-01-14 18:01:29.000000 UTC,2018-01-14 18:01:36.000000 UTC,2018-01-14 18:02:14.000000 UTC,...,1,TRUCK,1,5,5,NaN,"(37.774092678704704, -122.44108442596955)",180142739-T06,37.774093,-122.441084
8490,180142729,T01,18006136,Alarms,2018-01-14,2018-01-14,2018-01-14 17:58:43.000000 UTC,2018-01-14 18:00:09.000000 UTC,2018-01-14 18:00:17.000000 UTC,2018-01-14 18:02:10.000000 UTC,...,1,TRUCK,3,3,6,NaN,"(37.78347684038751, -122.4124351407277)",180142729-T01,37.783477,-122.412435
1997,180223489,T01,18009469,Structure Fire,2018-01-22,2018-01-22,2018-01-22 20:05:15.000000 UTC,2018-01-22 20:05:15.000000 UTC,2018-01-22 20:05:21.000000 UTC,2018-01-22 20:07:17.000000 UTC,...,1,TRUCK,3,3,6,NaN,"(37.78778674234962, -122.40307088677874)",180223489-T01,37.787787,-122.403071
8487,180141158,T13,18005977,Medical Incident,2018-01-14,2018-01-14,2018-01-14 10:42:12.000000 UTC,2018-01-14 10:42:12.000000 UTC,2018-01-14 10:43:01.000000 UTC,2018-01-14 10:43:24.000000 UTC,...,1,TRUCK,1,1,3,NaN,"(37.79705855398941, -122.40603020907437)",180141158-T13,37.797059,-122.406030
8435,180141510,T07,18006015,Alarms,2018-01-14,2018-01-14,2018-01-14 12:22:33.000000 UTC,2018-01-14 12:23:38.000000 UTC,2018-01-14 12:24:01.000000 UTC,2018-01-14 12:26:37.000000 UTC,...,1,TRUCK,2,6,9,NaN,"(37.75809277464886, -122.41468474542069)",180141510-T07,37.758093,-122.414685
2002,180220171,T02,18009141,Structure Fire,2018-01-22,2018-01-21,2018-01-22 02:10:45.000000 UTC,2018-01-22 02:10:45.000000 UTC,2018-01-22 02:10:51.000000 UTC,2018-01-22 02:13:46.000000 UTC,...,1,TRUCK,2,1,3,NaN,"(37.79670390276714, -122.40843088814951)",180220171-T02,37.796704,-122.408431
8481,180141888,T05,18006062,Medical Incident,2018-01-14,2018-01-14,2018-01-14 14:24:05.000000 UTC,2018-01-14 14:25:00.000000 UTC,2018-01-14 14:25:34.000000 UTC,2018-01-14 14:28:30.000000 UTC,...,1,TRUCK,3,5,5,NaN,"(37.78188029340187, -122.4324905130377)",180141888-T05,37.781880,-122.432491
8473,180142576,T03,18006120,Structure Fire,2018-01-14,2018-01-14,2018-01-14 17:22:53.000000 UTC,2018-01-14 17:24:17.000000 UTC,2018-01-14 17:24:29.000000 UTC,2018-01-14 17:24:46.000000 UTC,...,1,TRUCK,6,4,2,NaN,"(37.79176907484416, -122.42942684673099)",180142576-T03,37.791769,-122.429427
4873,180192667,T01,18008164,Citizen Assist / Service Call,2018-01-19,2018-01-19,2018-01-19 16:32:56.000000 UTC,2018-01-19 16:32:56.000000 UTC,2018-01-19 16:33:31.000000 UTC,2018-01-19 16:34:52.000000 UTC,...,1,TRUCK,1,1,3,NaN,"(37.79058656943533, -122.39987748080281)",180192667-T01,37.790587,-122.399877
8468,180143764,T03,18006243,Alarms,2018-01-14,2018-01-14,2018-01-14 23:23:51.000000 UTC,2018-01-14 23:25:54.000000 UTC,2018-01-14 23:26:12.000000 UTC,2018-01-14 23:27:51.000000 UTC,...,1,TRUCK,2,2,6,NaN,"(37.78284503447399, -122.41322176673785)",180143764-T03,37.782845,-122.413222
4868,180192619,T15,18008159,Structure Fire,2018-01-19,2018-01-19,2018-01-19 16:23:13.000000 UTC,2018-01-19 16:23:13.000000 UTC,2018-01-19 16:23:21.000000 UTC,2018-01-19 16:25:15.000000 UTC,...,1,TRUCK,2,9,11,NaN,"(37.72623624497357, -122.43362359229289)",180192619-T15,37.726236,-122.433624
8460,180143556,T09,18006227,Alarms,2018-01-14,2018-01-14,2018-01-14 22:11:16.000000 UTC,2018-01-14 22:13:22.000000 UTC,2018-01-14 22:13:38.000000 UTC,2018-01-14 22:15:04.000000 UTC,...,1,TRUCK,2,6,9,NaN,"(37.7497416991631, -122.40739562751031)",180143556-T09,37.749742,-122.407396
2038,180220828,T01,18009210,Gas Leak (Natural and LP Gases),2018-01-22,2018-01-22,2018-01-22 09:01:28.000000 UTC,2018-01-22 09:01:45.000000 UTC,2018-01-22 09:03:15.000000 UTC,2018-01-22 09:04:17.000000 UTC,...,1,TRUCK,2,4,3,NaN,"(37.787277154617044, -122.41682519978644)",180220828-T01,37.787277,-122.416825
8453,180143511,T17,18006222,Alarms,2018-01-14,2018-01-14,2018-01-14 21:57:57.000000 UTC,2018-01-14 22:00:39.000000 UTC,2018-01-14 22:01:03.000000 UTC,2018-01-14 22:02:10.000000 UTC,...,1,TRUCK,2,10,10,NaN,"(37.72881556768414, -122.3803270134155)",180143511-T17,37.728816,-122.380327
6262,180173914,T06,18007465,Structure Fire,2018-01-17,2018-01-17,2018-01-17 20:54:17.000000 UTC,2018-01-17 20:55:30.000000 UTC,2018-01-17 20:56:01.000000 UTC,2018-01-17 20:57:48.000000 UTC,...,1,TRUCK,2,2,8,NaN,"(37.765936328298, -122.43096263568948)",180173914-T06,37.765936,-122.430963
2009,180221177,T18,18009246,Medical Incident,2018-01-22,2018-01-22,2018-01-22 10:31:32.000000 UTC,2018-01-22 10:31:32.000000 UTC,2018-01-22 10:31:32.000000 UTC,2018-01-22 10:31:32.000000 UTC,...,1,TRUCK,1,7,4,NaN,"(37.764000834194064, -122.51034131805515)",180221177-T18,37.764001,-122.510341
4999,180192032,T03,18008103,Alarms,2018-01-19,2018-01-19,2018-01-19 14:03:11.000000 UTC,2018-01-19 14:04:25.000000 UTC,2018-01-19 14:05:55.000000 UTC,2018-01-19 14:05:55.000000 UTC,...,1,TRUCK,1,1,6,NaN,"(37.78626844171618, -122.41299723589641)",180192032-T03,37.786268,-122.412997

In [9]:
df = dataFrame[['call_type','unit_type','latitude','longitude']]
df = df[(df.call_type != 'Medical Incident') & (df.call_type != 'Alarms') & (df.call_type != 'Structure Fire')]
dfmed = df[df.call_type == 'Medical Incident']
dfala = df[df.call_type == 'Alarms']
dfstr = df[df.call_type == 'Structure Fire']
df.head()

                          call_type unit_type   latitude   longitude
6809  Citizen Assist / Service Call    ENGINE  37.751210 -122.481567
5761  Citizen Assist / Service Call     MEDIC  37.745956 -122.454240
4007  Citizen Assist / Service Call    ENGINE  37.777083 -122.416979
5005  Citizen Assist / Service Call    ENGINE  37.770958 -122.468301
7381  Citizen Assist / Service Call     MEDIC  37.786005 -122.395077

In [10]:
df.to_csv('OtherMapData.csv')
dfmed.to_csv('Medical.csv')
dfala.to_csv('Alarms.csv')
dfstr.to_csv('Fire.csv')

In [16]:
unitContents = []
unitContents = dataFrame.unit_type.value_counts()
unitContents

ENGINE            3589
MEDIC             3066
PRIVATE           1154
TRUCK              981
CHIEF              726
RESCUE CAPTAIN     272
RESCUE SQUAD       168
SUPPORT             33
INVESTIGATION       11
Name: unit_type, dtype: int64

In [46]:
typeContents = []
typeContents = dataFrame.call_type.value_counts();

Medical Incident                   6791
Alarms                             1061
Structure Fire                     1029
Traffic Collision                   410
Outside Fire                        144
Other                               129
Citizen Assist / Service Call       114
Gas Leak (Natural and LP Gases)      86
Train / Rail Incident                55
Water Rescue                         54
Vehicle Fire                         45
Elevator / Escalator Rescue          23
Electrical Hazard                    21
Smoke Investigation (Outside)        15
Odor (Strange / Unknown)             10
Fuel Spill                           10
HazMat                                3
Name: call_type, dtype: int64

In [1]:
typeContents.to_csv('TypeContents.csv')

NameError: name 'typeContents' is not defined

In [2]:
mapData = data[['call_type','latitude','longitude']]

NameError: name 'data' is not defined

In [54]:
mapData.to_csv('MapData.csv')

In [4]:
import pandas as pd
import numpy as np

In [7]:
mapdata = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/MapData.csv')
mapdata

      Unnamed: 0          call_type   latitude   longitude
0              0   Medical Incident  37.774442 -122.504679
1              1   Medical Incident  37.774095 -122.420001
2              2   Medical Incident  37.755218 -122.475540
3              3             Alarms  37.790319 -122.423163
4              4             Alarms  37.777328 -122.393089
5              5             Alarms  37.756890 -122.422229
6              6     Structure Fire  37.783359 -122.416695
7              7  Traffic Collision  37.769244 -122.408007
8              8             Alarms  37.807120 -122.416428
9              9   Medical Incident  37.712150 -122.417141
10            10   Medical Incident  37.778832 -122.415642
11            11   Medical Incident  37.797092 -122.398333
12            12   Medical Incident  37.756096 -122.427783
13            13   Medical Incident  37.780792 -122.408386
14            14   Medical Incident  37.752239 -122.418445
15            15     Structure Fire  37.785217 -122.417070
16            16   Medical Incident  37.779523 -122.412639
17            17   Medical Incident  37.748173 -122.458695
18            18   Medical Incident  37.770055 -122.446128
19            19     Structure Fire  37.783359 -122.416695
20            20   Medical Incident  37.777790 -122.412834
21            21   Medical Incident  37.780669 -122.401678
22            22   Medical Incident  37.774093 -122.441084
23            23   Medical Incident  37.802828 -122.413034
24            24   Medical Incident  37.786268 -122.412997
25            25   Medical Incident  37.770273 -122.448605
26            26   Medical Incident  37.781914 -122.413032
27            27              Other  37.722298 -122.411303
28            28   Medical Incident  37.759628 -122.415923
29            29   Medical Incident  37.781865 -122.414285
...          ...                ...        ...         ...
9970        9970   Medical Incident  37.761777 -122.435152
9971        9971   Medical Incident  37.742020 -122.477839
9972        9972  Traffic Collision  37.731820 -122.405412
9973        9973   Medical Incident  37.782444 -122.420575
9974        9974   Medical Incident  37.720458 -122.437031
9975        9975   Medical Incident  37.783310 -122.388380
9976        9976   Medical Incident  37.774870 -122.394417
9977        9977   Medical Incident  37.804809 -122.406796
9978        9978   Medical Incident  37.719868 -122.390905
9979        9979   Medical Incident  37.781168 -122.434806
9980        9980     Structure Fire  37.766134 -122.421935
9981        9981   Medical Incident  37.782444 -122.420575
9982        9982  Traffic Collision  37.810521 -122.365138
9983        9983   Medical Incident  37.797298 -122.433847
9984        9984   Medical Incident  37.776097 -122.408564
9985        9985   Medical Incident  37.750118 -122.390433
9986        9986   Medical Incident  37.760638 -122.425844
9987        9987   Medical Incident  37.779956 -122.466427
9988        9988   Medical Incident  37.768154 -122.454312
9989        9989   Medical Incident  37.791835 -122.410818
9990        9990              Other  37.767192 -122.431222
9991        9991   Medical Incident  37.775885 -122.430365
9992        9992  Traffic Collision  37.771286 -122.413204
9993        9993   Medical Incident  37.761514 -122.425556
9994        9994   Medical Incident  37.749102 -122.486927
9995        9995   Medical Incident  37.757970 -122.416727
9996        9996   Medical Incident  37.787082 -122.425868
9997        9997   Medical Incident  37.784206 -122.407613
9998        9998       Water Rescue  37.805163 -122.432957
9999        9999   Medical Incident  37.785582 -122.414617

[10000 rows x 4 columns]

In [10]:
updatemapdata = mapdata[(mapdata.call_type == 'Medical Incident') | (mapdata.call_type == 'Alarms') |(mapdata.call_type == 'Structure Fire')]

In [11]:
updatemapdata

      Unnamed: 0         call_type   latitude   longitude
0              0  Medical Incident  37.774442 -122.504679
1              1  Medical Incident  37.774095 -122.420001
2              2  Medical Incident  37.755218 -122.475540
3              3            Alarms  37.790319 -122.423163
4              4            Alarms  37.777328 -122.393089
5              5            Alarms  37.756890 -122.422229
6              6    Structure Fire  37.783359 -122.416695
8              8            Alarms  37.807120 -122.416428
9              9  Medical Incident  37.712150 -122.417141
10            10  Medical Incident  37.778832 -122.415642
11            11  Medical Incident  37.797092 -122.398333
12            12  Medical Incident  37.756096 -122.427783
13            13  Medical Incident  37.780792 -122.408386
14            14  Medical Incident  37.752239 -122.418445
15            15    Structure Fire  37.785217 -122.417070
16            16  Medical Incident  37.779523 -122.412639
17            17  Medical Incident  37.748173 -122.458695
18            18  Medical Incident  37.770055 -122.446128
19            19    Structure Fire  37.783359 -122.416695
20            20  Medical Incident  37.777790 -122.412834
21            21  Medical Incident  37.780669 -122.401678
22            22  Medical Incident  37.774093 -122.441084
23            23  Medical Incident  37.802828 -122.413034
24            24  Medical Incident  37.786268 -122.412997
25            25  Medical Incident  37.770273 -122.448605
26            26  Medical Incident  37.781914 -122.413032
28            28  Medical Incident  37.759628 -122.415923
29            29  Medical Incident  37.781865 -122.414285
30            30  Medical Incident  37.779383 -122.418484
31            31  Medical Incident  37.791546 -122.420037
...          ...               ...        ...         ...
9963        9963            Alarms  37.793488 -122.398206
9964        9964    Structure Fire  37.786268 -122.412997
9966        9966    Structure Fire  37.776464 -122.426263
9967        9967    Structure Fire  37.766134 -122.421935
9968        9968  Medical Incident  37.760085 -122.434996
9970        9970  Medical Incident  37.761777 -122.435152
9971        9971  Medical Incident  37.742020 -122.477839
9973        9973  Medical Incident  37.782444 -122.420575
9974        9974  Medical Incident  37.720458 -122.437031
9975        9975  Medical Incident  37.783310 -122.388380
9976        9976  Medical Incident  37.774870 -122.394417
9977        9977  Medical Incident  37.804809 -122.406796
9978        9978  Medical Incident  37.719868 -122.390905
9979        9979  Medical Incident  37.781168 -122.434806
9980        9980    Structure Fire  37.766134 -122.421935
9981        9981  Medical Incident  37.782444 -122.420575
9983        9983  Medical Incident  37.797298 -122.433847
9984        9984  Medical Incident  37.776097 -122.408564
9985        9985  Medical Incident  37.750118 -122.390433
9986        9986  Medical Incident  37.760638 -122.425844
9987        9987  Medical Incident  37.779956 -122.466427
9988        9988  Medical Incident  37.768154 -122.454312
9989        9989  Medical Incident  37.791835 -122.410818
9991        9991  Medical Incident  37.775885 -122.430365
9993        9993  Medical Incident  37.761514 -122.425556
9994        9994  Medical Incident  37.749102 -122.486927
9995        9995  Medical Incident  37.757970 -122.416727
9996        9996  Medical Incident  37.787082 -122.425868
9997        9997  Medical Incident  37.784206 -122.407613
9999        9999  Medical Incident  37.785582 -122.414617

[8881 rows x 4 columns]

In [23]:
updatemapdata.insert(4,'marker-color', len(updatemapdata))

ValueError: cannot insert marker-color, already exists

In [21]:
updatemapdata

      Unnamed: 0         call_type   latitude   longitude  marker-color
0              0  Medical Incident  37.774442 -122.504679          8881
1              1  Medical Incident  37.774095 -122.420001          8881
2              2  Medical Incident  37.755218 -122.475540          8881
3              3            Alarms  37.790319 -122.423163          8881
4              4            Alarms  37.777328 -122.393089          8881
5              5            Alarms  37.756890 -122.422229          8881
6              6    Structure Fire  37.783359 -122.416695          8881
8              8            Alarms  37.807120 -122.416428          8881
9              9  Medical Incident  37.712150 -122.417141          8881
10            10  Medical Incident  37.778832 -122.415642          8881
11            11  Medical Incident  37.797092 -122.398333          8881
12            12  Medical Incident  37.756096 -122.427783          8881
13            13  Medical Incident  37.780792 -122.408386          8881
14            14  Medical Incident  37.752239 -122.418445          8881
15            15    Structure Fire  37.785217 -122.417070          8881
16            16  Medical Incident  37.779523 -122.412639          8881
17            17  Medical Incident  37.748173 -122.458695          8881
18            18  Medical Incident  37.770055 -122.446128          8881
19            19    Structure Fire  37.783359 -122.416695          8881
20            20  Medical Incident  37.777790 -122.412834          8881
21            21  Medical Incident  37.780669 -122.401678          8881
22            22  Medical Incident  37.774093 -122.441084          8881
23            23  Medical Incident  37.802828 -122.413034          8881
24            24  Medical Incident  37.786268 -122.412997          8881
25            25  Medical Incident  37.770273 -122.448605          8881
26            26  Medical Incident  37.781914 -122.413032          8881
28            28  Medical Incident  37.759628 -122.415923          8881
29            29  Medical Incident  37.781865 -122.414285          8881
30            30  Medical Incident  37.779383 -122.418484          8881
31            31  Medical Incident  37.791546 -122.420037          8881
...          ...               ...        ...         ...           ...
9963        9963            Alarms  37.793488 -122.398206          8881
9964        9964    Structure Fire  37.786268 -122.412997          8881
9966        9966    Structure Fire  37.776464 -122.426263          8881
9967        9967    Structure Fire  37.766134 -122.421935          8881
9968        9968  Medical Incident  37.760085 -122.434996          8881
9970        9970  Medical Incident  37.761777 -122.435152          8881
9971        9971  Medical Incident  37.742020 -122.477839          8881
9973        9973  Medical Incident  37.782444 -122.420575          8881
9974        9974  Medical Incident  37.720458 -122.437031          8881
9975        9975  Medical Incident  37.783310 -122.388380          8881
9976        9976  Medical Incident  37.774870 -122.394417          8881
9977        9977  Medical Incident  37.804809 -122.406796          8881
9978        9978  Medical Incident  37.719868 -122.390905          8881
9979        9979  Medical Incident  37.781168 -122.434806          8881
9980        9980    Structure Fire  37.766134 -122.421935          8881
9981        9981  Medical Incident  37.782444 -122.420575          8881
9983        9983  Medical Incident  37.797298 -122.433847          8881
9984        9984  Medical Incident  37.776097 -122.408564          8881
9985        9985  Medical Incident  37.750118 -122.390433          8881
9986        9986  Medical Incident  37.760638 -122.425844          8881
9987        9987  Medical Incident  37.779956 -122.466427          8881
9988        9988  Medical Incident  37.768154 -122.454312          8881
9989        9989  Medical Incident  37.791835 -122.410818          8881
9991        9991  Medical Incident  37.775885 -122.430365          8881
9993        9993  Medical Incident  37.761514 -122.425556          8881
9994        9994  Medical Incident  37.749102 -122.486927          8881
9995        9995  Medical Incident  37.757970 -122.416727          8881
9996        9996  Medical Incident  37.787082 -122.425868          8881
9997        9997  Medical Incident  37.784206 -122.407613          8881
9999        9999  Medical Incident  37.785582 -122.414617          8881

[8881 rows x 5 columns]

In [25]:
del updatemapdata['marker-color']
updatemapdata

      Unnamed: 0         call_type   latitude   longitude
0              0  Medical Incident  37.774442 -122.504679
1              1  Medical Incident  37.774095 -122.420001
2              2  Medical Incident  37.755218 -122.475540
3              3            Alarms  37.790319 -122.423163
4              4            Alarms  37.777328 -122.393089
5              5            Alarms  37.756890 -122.422229
6              6    Structure Fire  37.783359 -122.416695
8              8            Alarms  37.807120 -122.416428
9              9  Medical Incident  37.712150 -122.417141
10            10  Medical Incident  37.778832 -122.415642
11            11  Medical Incident  37.797092 -122.398333
12            12  Medical Incident  37.756096 -122.427783
13            13  Medical Incident  37.780792 -122.408386
14            14  Medical Incident  37.752239 -122.418445
15            15    Structure Fire  37.785217 -122.417070
16            16  Medical Incident  37.779523 -122.412639
17            17  Medical Incident  37.748173 -122.458695
18            18  Medical Incident  37.770055 -122.446128
19            19    Structure Fire  37.783359 -122.416695
20            20  Medical Incident  37.777790 -122.412834
21            21  Medical Incident  37.780669 -122.401678
22            22  Medical Incident  37.774093 -122.441084
23            23  Medical Incident  37.802828 -122.413034
24            24  Medical Incident  37.786268 -122.412997
25            25  Medical Incident  37.770273 -122.448605
26            26  Medical Incident  37.781914 -122.413032
28            28  Medical Incident  37.759628 -122.415923
29            29  Medical Incident  37.781865 -122.414285
30            30  Medical Incident  37.779383 -122.418484
31            31  Medical Incident  37.791546 -122.420037
...          ...               ...        ...         ...
9963        9963            Alarms  37.793488 -122.398206
9964        9964    Structure Fire  37.786268 -122.412997
9966        9966    Structure Fire  37.776464 -122.426263
9967        9967    Structure Fire  37.766134 -122.421935
9968        9968  Medical Incident  37.760085 -122.434996
9970        9970  Medical Incident  37.761777 -122.435152
9971        9971  Medical Incident  37.742020 -122.477839
9973        9973  Medical Incident  37.782444 -122.420575
9974        9974  Medical Incident  37.720458 -122.437031
9975        9975  Medical Incident  37.783310 -122.388380
9976        9976  Medical Incident  37.774870 -122.394417
9977        9977  Medical Incident  37.804809 -122.406796
9978        9978  Medical Incident  37.719868 -122.390905
9979        9979  Medical Incident  37.781168 -122.434806
9980        9980    Structure Fire  37.766134 -122.421935
9981        9981  Medical Incident  37.782444 -122.420575
9983        9983  Medical Incident  37.797298 -122.433847
9984        9984  Medical Incident  37.776097 -122.408564
9985        9985  Medical Incident  37.750118 -122.390433
9986        9986  Medical Incident  37.760638 -122.425844
9987        9987  Medical Incident  37.779956 -122.466427
9988        9988  Medical Incident  37.768154 -122.454312
9989        9989  Medical Incident  37.791835 -122.410818
9991        9991  Medical Incident  37.775885 -122.430365
9993        9993  Medical Incident  37.761514 -122.425556
9994        9994  Medical Incident  37.749102 -122.486927
9995        9995  Medical Incident  37.757970 -122.416727
9996        9996  Medical Incident  37.787082 -122.425868
9997        9997  Medical Incident  37.784206 -122.407613
9999        9999  Medical Incident  37.785582 -122.414617

[8881 rows x 4 columns]

In [33]:
marker = []
for row in updatemapdata['call_type']:
    if (updatemapdata.isin*'Medical Incident'):
        marker.append('#ff0000')
    elif (updatemapdata.isin('Alarms'):
        marker.append('#0000ff')
    elif (updatemapdata.isin('Structure Fire'):
        marker.append('#ffffff')
    else: 
        marker.append('0')

updatamapdata['marker-color'] = marker

SyntaxError: invalid syntax (<ipython-input-33-8721bc9034f2>, line 5)

In [45]:
data = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/sfpd-dispatch/sfpd_dispatch_data_subset.csv');
mapData = data[['call_type','latitude', 'longitude']]
mapData

              call_type   latitude   longitude
0      Medical Incident  37.774442 -122.504679
1      Medical Incident  37.774095 -122.420001
2      Medical Incident  37.755218 -122.475540
3                Alarms  37.790319 -122.423163
4                Alarms  37.777328 -122.393089
5                Alarms  37.756890 -122.422229
6        Structure Fire  37.783359 -122.416695
7     Traffic Collision  37.769244 -122.408007
8                Alarms  37.807120 -122.416428
9      Medical Incident  37.712150 -122.417141
10     Medical Incident  37.778832 -122.415642
11     Medical Incident  37.797092 -122.398333
12     Medical Incident  37.756096 -122.427783
13     Medical Incident  37.780792 -122.408386
14     Medical Incident  37.752239 -122.418445
15       Structure Fire  37.785217 -122.417070
16     Medical Incident  37.779523 -122.412639
17     Medical Incident  37.748173 -122.458695
18     Medical Incident  37.770055 -122.446128
19       Structure Fire  37.783359 -122.416695
20     Medical Incident  37.777790 -122.412834
21     Medical Incident  37.780669 -122.401678
22     Medical Incident  37.774093 -122.441084
23     Medical Incident  37.802828 -122.413034
24     Medical Incident  37.786268 -122.412997
25     Medical Incident  37.770273 -122.448605
26     Medical Incident  37.781914 -122.413032
27                Other  37.722298 -122.411303
28     Medical Incident  37.759628 -122.415923
29     Medical Incident  37.781865 -122.414285
...                 ...        ...         ...
9970   Medical Incident  37.761777 -122.435152
9971   Medical Incident  37.742020 -122.477839
9972  Traffic Collision  37.731820 -122.405412
9973   Medical Incident  37.782444 -122.420575
9974   Medical Incident  37.720458 -122.437031
9975   Medical Incident  37.783310 -122.388380
9976   Medical Incident  37.774870 -122.394417
9977   Medical Incident  37.804809 -122.406796
9978   Medical Incident  37.719868 -122.390905
9979   Medical Incident  37.781168 -122.434806
9980     Structure Fire  37.766134 -122.421935
9981   Medical Incident  37.782444 -122.420575
9982  Traffic Collision  37.810521 -122.365138
9983   Medical Incident  37.797298 -122.433847
9984   Medical Incident  37.776097 -122.408564
9985   Medical Incident  37.750118 -122.390433
9986   Medical Incident  37.760638 -122.425844
9987   Medical Incident  37.779956 -122.466427
9988   Medical Incident  37.768154 -122.454312
9989   Medical Incident  37.791835 -122.410818
9990              Other  37.767192 -122.431222
9991   Medical Incident  37.775885 -122.430365
9992  Traffic Collision  37.771286 -122.413204
9993   Medical Incident  37.761514 -122.425556
9994   Medical Incident  37.749102 -122.486927
9995   Medical Incident  37.757970 -122.416727
9996   Medical Incident  37.787082 -122.425868
9997   Medical Incident  37.784206 -122.407613
9998       Water Rescue  37.805163 -122.432957
9999   Medical Incident  37.785582 -122.414617

[10000 rows x 3 columns]

In [37]:
mapData.to_csv('MapData.csv')

In [50]:
a = mapData[mapData.call_type == 'Medical Incident']
a

             call_type   latitude   longitude
0     Medical Incident  37.774442 -122.504679
1     Medical Incident  37.774095 -122.420001
2     Medical Incident  37.755218 -122.475540
9     Medical Incident  37.712150 -122.417141
10    Medical Incident  37.778832 -122.415642
11    Medical Incident  37.797092 -122.398333
12    Medical Incident  37.756096 -122.427783
13    Medical Incident  37.780792 -122.408386
14    Medical Incident  37.752239 -122.418445
16    Medical Incident  37.779523 -122.412639
17    Medical Incident  37.748173 -122.458695
18    Medical Incident  37.770055 -122.446128
20    Medical Incident  37.777790 -122.412834
21    Medical Incident  37.780669 -122.401678
22    Medical Incident  37.774093 -122.441084
23    Medical Incident  37.802828 -122.413034
24    Medical Incident  37.786268 -122.412997
25    Medical Incident  37.770273 -122.448605
26    Medical Incident  37.781914 -122.413032
28    Medical Incident  37.759628 -122.415923
29    Medical Incident  37.781865 -122.414285
30    Medical Incident  37.779383 -122.418484
31    Medical Incident  37.791546 -122.420037
33    Medical Incident  37.773190 -122.418237
34    Medical Incident  37.720947 -122.453165
35    Medical Incident  37.784978 -122.459698
36    Medical Incident  37.788945 -122.426252
37    Medical Incident  37.742261 -122.421965
38    Medical Incident  37.785744 -122.405831
39    Medical Incident  37.783260 -122.418366
...                ...        ...         ...
9955  Medical Incident  37.799843 -122.436046
9956  Medical Incident  37.737956 -122.421913
9959  Medical Incident  37.766545 -122.395061
9961  Medical Incident  37.761514 -122.425556
9962  Medical Incident  37.796335 -122.400515
9968  Medical Incident  37.760085 -122.434996
9970  Medical Incident  37.761777 -122.435152
9971  Medical Incident  37.742020 -122.477839
9973  Medical Incident  37.782444 -122.420575
9974  Medical Incident  37.720458 -122.437031
9975  Medical Incident  37.783310 -122.388380
9976  Medical Incident  37.774870 -122.394417
9977  Medical Incident  37.804809 -122.406796
9978  Medical Incident  37.719868 -122.390905
9979  Medical Incident  37.781168 -122.434806
9981  Medical Incident  37.782444 -122.420575
9983  Medical Incident  37.797298 -122.433847
9984  Medical Incident  37.776097 -122.408564
9985  Medical Incident  37.750118 -122.390433
9986  Medical Incident  37.760638 -122.425844
9987  Medical Incident  37.779956 -122.466427
9988  Medical Incident  37.768154 -122.454312
9989  Medical Incident  37.791835 -122.410818
9991  Medical Incident  37.775885 -122.430365
9993  Medical Incident  37.761514 -122.425556
9994  Medical Incident  37.749102 -122.486927
9995  Medical Incident  37.757970 -122.416727
9996  Medical Incident  37.787082 -122.425868
9997  Medical Incident  37.784206 -122.407613
9999  Medical Incident  37.785582 -122.414617

[6791 rows x 3 columns]

In [46]:
b = mapData[mapData.call_type == 'Alarms']

In [47]:
c = mapData[mapData.call_type == 'Structure Fire']

In [48]:
c

           call_type   latitude   longitude
6     Structure Fire  37.783359 -122.416695
15    Structure Fire  37.785217 -122.417070
19    Structure Fire  37.783359 -122.416695
32    Structure Fire  37.770259 -122.431832
51    Structure Fire  37.798603 -122.423149
58    Structure Fire  37.798603 -122.423149
72    Structure Fire  37.774284 -122.467088
75    Structure Fire  37.770259 -122.431832
78    Structure Fire  37.770259 -122.431832
100   Structure Fire  37.790495 -122.402353
104   Structure Fire  37.774284 -122.467088
108   Structure Fire  37.798603 -122.423149
152   Structure Fire  37.798603 -122.423149
171   Structure Fire  37.807690 -122.412330
174   Structure Fire  37.786410 -122.408036
177   Structure Fire  37.755998 -122.409433
186   Structure Fire  37.783359 -122.416695
202   Structure Fire  37.790495 -122.402353
208   Structure Fire  37.755998 -122.409433
226   Structure Fire  37.770259 -122.431832
233   Structure Fire  37.807690 -122.412330
252   Structure Fire  37.807690 -122.412330
260   Structure Fire  37.785217 -122.417070
262   Structure Fire  37.774284 -122.467088
267   Structure Fire  37.783359 -122.416695
289   Structure Fire  37.798603 -122.423149
292   Structure Fire  37.785217 -122.417070
293   Structure Fire  37.790495 -122.402353
298   Structure Fire  37.716460 -122.441020
313   Structure Fire  37.785217 -122.417070
...              ...        ...         ...
9702  Structure Fire  37.786060 -122.414644
9724  Structure Fire  37.786268 -122.412997
9725  Structure Fire  37.786060 -122.414644
9733  Structure Fire  37.712196 -122.420839
9743  Structure Fire  37.766134 -122.421935
9752  Structure Fire  37.766134 -122.421935
9753  Structure Fire  37.786268 -122.412997
9761  Structure Fire  37.778251 -122.419883
9779  Structure Fire  37.765051 -122.419669
9791  Structure Fire  37.766134 -122.421935
9794  Structure Fire  37.733118 -122.457641
9808  Structure Fire  37.766134 -122.421935
9811  Structure Fire  37.786060 -122.414644
9823  Structure Fire  37.765051 -122.419669
9830  Structure Fire  37.726926 -122.430965
9832  Structure Fire  37.733118 -122.457641
9847  Structure Fire  37.769798 -122.448579
9880  Structure Fire  37.733118 -122.457641
9884  Structure Fire  37.769798 -122.448579
9885  Structure Fire  37.712196 -122.420839
9900  Structure Fire  37.786060 -122.414644
9924  Structure Fire  37.733118 -122.457641
9941  Structure Fire  37.712196 -122.420839
9943  Structure Fire  37.786268 -122.412997
9951  Structure Fire  37.786268 -122.412997
9960  Structure Fire  37.733118 -122.457641
9964  Structure Fire  37.786268 -122.412997
9966  Structure Fire  37.776464 -122.426263
9967  Structure Fire  37.766134 -122.421935
9980  Structure Fire  37.766134 -122.421935

[1029 rows x 3 columns]

In [51]:
a.to_csv('Medical.csv')
b.to_csv('Alarms.csv')
c.to_csv('Fire.csv')