In [28]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/sfpd-dispatch/sfpd_dispatch_data_subset.csv');
data

,call_number,unit_id,incident_number,call_type,call_date,watch_date,received_timestamp,entry_timestamp,dispatch_timestamp,response_timestamp,...,number_of_alarms,unit_type,unit_sequence_in_call_dispatch,fire_prevention_district,supervisor_district,neighborhood_district,location,row_id,latitude,longitude
0,180243072,84,18010216,Medical Incident,2018-01-24,2018-01-24,2018-01-24 17:36:16.000000 UTC,2018-01-24 17:38:21.000000 UTC,2018-01-24 17:39:41.000000 UTC,2018-01-24 17:39:45.000000 UTC,...,1,MEDIC,1,7,1,NaN,"(37.77444199483868, -122.5046792231959)",180243072-84,37.774442,-122.504679
1,180240538,61,18010011,Medical Incident,2018-01-24,2018-01-23,2018-01-24 07:05:05.000000 UTC,2018-01-24 07:05:05.000000 UTC,2018-01-24 07:05:31.000000 UTC,2018-01-24 07:05:45.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.774094856688166, -122.42000143696421)",180240538-61,37.774095,-122.420001
2,180240176,E22,18009959,Medical Incident,2018-01-24,2018-01-23,2018-01-24 02:04:21.000000 UTC,2018-01-24 02:05:37.000000 UTC,2018-01-24 02:06:04.000000 UTC,2018-01-24 02:07:26.000000 UTC,...,1,ENGINE,1,8,7,NaN,"(37.75521795168784, -122.47554039050351)",180240176-E22,37.755218,-122.475540
3,180243588,E03,18010271,Alarms,2018-01-24,2018-01-24,2018-01-24 20:04:15.000000 UTC,2018-01-24 20:05:12.000000 UTC,2018-01-24 20:05:24.000000 UTC,2018-01-24 20:05:36.000000 UTC,...,1,ENGINE,1,4,2,NaN,"(37.79031930341935, -122.4231629067995)",180243588-E03,37.790319,-122.423163
4,180243590,B03,18010272,Alarms,2018-01-24,2018-01-24,2018-01-24 20:03:08.000000 UTC,2018-01-24 20:05:36.000000 UTC,2018-01-24 20:05:57.000000 UTC,2018-01-24 20:06:56.000000 UTC,...,1,CHIEF,3,3,6,NaN,"(37.77732776352611, -122.39308855968541)",180243590-B03,37.777328,-122.393089
5,180243782,E07,18010292,Alarms,2018-01-24,2018-01-24,2018-01-24 21:18:56.000000 UTC,2018-01-24 21:20:21.000000 UTC,2018-01-24 21:21:18.000000 UTC,2018-01-24 21:22:36.000000 UTC,...,1,ENGINE,1,6,8,NaN,"(37.756890170572206, -122.42222930549926)",180243782-E07,37.756890,-122.422229
6,180241852,E03,18010114,Structure Fire,2018-01-24,2018-01-24,2018-01-24 12:24:27.000000 UTC,2018-01-24 12:25:27.000000 UTC,2018-01-24 12:26:56.000000 UTC,2018-01-24 12:26:56.000000 UTC,...,1,ENGINE,8,2,6,NaN,"(37.783359002692066, -122.41669494404806)",180241852-E03,37.783359,-122.416695
7,180243546,66,18010265,Traffic Collision,2018-01-24,2018-01-24,2018-01-24 19:51:29.000000 UTC,2018-01-24 19:53:19.000000 UTC,2018-01-24 19:53:41.000000 UTC,2018-01-24 19:53:50.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.76924401107554, -122.40800720584919)",180243546-66,37.769244,-122.408007
8,180243952,E28,18010317,Alarms,2018-01-24,2018-01-24,2018-01-24 22:26:22.000000 UTC,2018-01-24 22:27:06.000000 UTC,2018-01-24 22:27:47.000000 UTC,2018-01-24 22:28:33.000000 UTC,...,1,ENGINE,1,1,3,NaN,"(37.80711992362169, -122.41642787206773)",180243952-E28,37.807120,-122.416428
9,180241350,58,18010067,Medical Incident,2018-01-24,2018-01-24,2018-01-24 10:35:00.000000 UTC,2018-01-24 10:36:55.000000 UTC,2018-01-24 10:37:06.000000 UTC,2018-01-24 10:37:09.000000 UTC,...,1,MEDIC,1,9,10,NaN,"(37.71214950882262, -122.41714122572772)",180241350-58,37.712150,-122.417141
10,180241957,53,18010125,Medical Incident,2018-01-24,2018-01-24,2018-01-24 12:53:39.000000 UTC,2018-01-24 12:53:39.000000 UTC,2018-01-24 12:55:17.000000 UTC,2018-01-24 12:55:28.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.77883231587925, -122.41564248785478)",180241957-53,37.778832,-122.415642
11,180242429,62,18010155,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:36:16.000000 UTC,2018-01-24 14:38:23.000000 UTC,2018-01-24 14:45:58.000000 UTC,2018-01-24 14:47:14.000000 UTC,...,1,MEDIC,1,1,3,NaN,"(37.79709205269086, -122.39833314918091)",180242429-62,37.797092,-122.398333
12,180243142,E11,18010223,Medical Incident,2018-01-24,2018-01-24,2018-01-24 17:56:16.000000 UTC,2018-01-24 17:58:32.000000 UTC,2018-01-24 17:59:52.000000 UTC,2018-01-24 18:00:50.000000 UTC,...,1,ENGINE,1,6,8,NaN,"(37.756096396025626, -122.42778335985659)",180243142-E11,37.756096,-122.427783
13,180242903,KM06,18010201,Medical Incident,2018-01-24,2018-01-24,2018-01-24 16:48:13.000000 UTC,2018-01-24 16:51:25.000000 UTC,2018-01-24 16:51:46.000000 UTC,2018-01-24 16:52:30.000000 UTC,...,1,PRIVATE,2,3,6,NaN,"(37.78079208027532, -122.40838574549893)",180242903-KM06,37.780792,-122.408386
14,180243517,85,18010262,Medical Incident,2018-01-24,2018-01-24,2018-01-24 19:41:44.000000 UTC,2018-01-24 19:44:22.000000 UTC,2018-01-24 19:45:15.000000 UTC,2018-01-24 19:45:21.000000 UTC,...,1,MEDIC,2,6,9,NaN,"(37.75223945497915, -122.41844527285122)",180243517-85,37.752239,-122.418445
15,180240052,RS1,18009942,Structure Fire,2018-01-24,2018-01-23,2018-01-24 00:19:30.000000 UTC,2018-01-24 00:34:51.000000 UTC,2018-01-24 00:35:09.000000 UTC,2018-01-24 00:36:32.000000 UTC,...,1,RESCUE SQUAD,6,2,6,NaN,"(37.78521736163072, -122.41706961139498)",180240052-RS1,37.785217,-122.417070
16,180241776,E03,18010110,Medical Incident,2018-01-24,2018-01-24,2018-01-24 12:08:29.000000 UTC,2018-01-24 12:10:03.000000 UTC,2018-01-24 12:10:43.000000 UTC,2018-01-24 12:11:43.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.77952317116152, -122.41263929179321)",180241776-E03,37.779523,-122.412639
17,180242487,E20,18010161,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:54:21.000000 UTC,2018-01-24 14:57:25.000000 UTC,2018-01-24 15:01:11.000000 UTC,2018-01-24 15:02:25.000000 UTC,...,1,ENGINE,1,8,7,NaN,"(37.74817254773626, -122.45869503396155)",180242487-E20,37.748173,-122.458695
18,180243850,72,18010301,Medical Incident,2018-01-24,2018-01-24,2018-01-24 21:42:22.000000 UTC,2018-01-24 21:46:48.000000 UTC,2018-01-24 21:47:16.000000 UTC,2018-01-24 21:47:21.000000 UTC,...,1,MEDIC,1,5,5,NaN,"(37.770054661455546, -122.44612843129843)",180243850-72,37.770055,-122.446128
19,180241852,T01,18010114,Structure Fire,2018-01-24,2018-01-24,2018-01-24 12:24:27.000000 UTC,2018-01-24 12:25:27.000000 UTC,2018-01-24 12:25:47.000000 UTC,2018-01-24 12:25:53.000000 UTC,...,1,TRUCK,10,2,6,NaN,"(37.783359002692066, -122.41669494404806)",180241852-T01,37.783359,-122.416695
20,180242322,64,18010144,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:10:45.000000 UTC,2018-01-24 14:11:48.000000 UTC,2018-01-24 14:12:10.000000 UTC,2018-01-24 14:12:16.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.77779030942458, -122.41283433212864)",180242322-64,37.777790,-122.412834
21,180241372,E01,18010072,Medical Incident,2018-01-24,2018-01-24,2018-01-24 10:40:14.000000 UTC,2018-01-24 10:41:06.000000 UTC,2018-01-24 10:41:22.000000 UTC,2018-01-24 10:42:30.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.78066916324976, -122.40167804559798)",180241372-E01,37.780669,-122.401678
22,180241696,E21,18010100,Medical Incident,2018-01-24,2018-01-24,2018-01-24 11:52:30.000000 UTC,2018-01-24 11:52:43.000000 UTC,2018-01-24 11:52:59.000000 UTC,2018-01-24 11:54:59.000000 UTC,...,1,ENGINE,1,5,5,NaN,"(37.774092678704704, -122.44108442596955)",180241696-E21,37.774093,-122.441084
23,180242478,E28,18010160,Medical Incident,2018-01-24,2018-01-24,2018-01-24 14:51:27.000000 UTC,2018-01-24 14:54:11.000000 UTC,2018-01-24 15:01:45.000000 UTC,2018-01-24 15:02:44.000000 UTC,...,1,ENGINE,1,1,3,NaN,"(37.80282769816514, -122.41303433677871)",180242478-E28,37.802828,-122.413034
24,180240880,79,18010040,Medical Incident,2018-01-24,2018-01-24,2018-01-24 08:50:47.000000 UTC,2018-01-24 08:52:11.000000 UTC,2018-01-24 08:52:29.000000 UTC,2018-01-24 08:52:36.000000 UTC,...,1,MEDIC,1,1,6,NaN,"(37.78626844171618, -122.41299723589641)",180240880-79,37.786268,-122.412997
25,180242627,52,18010178,Medical Incident,2018-01-24,2018-01-24,2018-01-24 15:31:54.000000 UTC,2018-01-24 15:32:57.000000 UTC,2018-01-24 15:33:39.000000 UTC,2018-01-24 15:34:32.000000 UTC,...,1,MEDIC,2,5,5,NaN,"(37.770273091358646, -122.4486050480563)",180242627-52,37.770273,-122.448605
26,180242103,52,18010133,Medical Incident,2018-01-24,2018-01-24,2018-01-24 13:19:28.000000 UTC,2018-01-24 13:21:23.000000 UTC,2018-01-24 13:22:11.000000 UTC,2018-01-24 13:22:20.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.78191397441793, -122.41303219395635)",180242103-52,37.781914,-122.413032
27,180243393,71,18010251,Other,2018-01-24,2018-01-24,2018-01-24 19:07:16.000000 UTC,2018-01-24 19:07:16.000000 UTC,2018-01-24 21:45:14.000000 UTC,2018-01-24 21:45:14.000000 UTC,...,1,MEDIC,2,9,9,NaN,"(37.72229807127346, -122.41130309997389)",180243393-71,37.722298,-122.411303
28,180240248,94,18009965,Medical Incident,2018-01-24,2018-01-23,2018-01-24 03:14:26.000000 UTC,2018-01-24 03:16:33.000000 UTC,2018-01-24 03:16:45.000000 UTC,2018-01-24 03:17:12.000000 UTC,...,1,MEDIC,1,6,9,NaN,"(37.75962769270459, -122.41592301840338)",180240248-94,37.759628,-122.415923
29,180241729,E36,18010106,Medical Incident,2018-01-24,2018-01-24,2018-01-24 11:59:40.000000 UTC,2018-01-24 12:00:40.000000 UTC,2018-01-24 12:01:55.000000 UTC,2018-01-24 12:01:55.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.78186544733037, -122.41428534642068)",180241729-E36,37.781865,-122.414285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9970,180132359,E05,18005688,Medical Incident,2018-01-13,2018-01-13,2018-01-13 15:51:50.000000 UTC,2018-01-13 15:52:14.000000 UTC,2018-01-13 15:52:34.000000 UTC,2018-01-13 15:53:24.000000 UTC,...,1,ENGINE,2,5,8,NaN,"(37.76177683437902, -122.43515167277485)",180132359-E05,37.761777,-122.435152
9971,180130474,E40,18005495,Medical Incident,2018-01-13,2018-01-12,2018-01-13 04:07:51.000000 UTC,2018-01-13 04:07:51.000000 UTC,2018-01-13 04:08:19.000000 UTC,2018-01-13 04:09:43.000000 UTC,...,1,ENGINE,1,8,4,NaN,"(37.74201996298055, -122.47783880287392)",180130474-E40,37.742020,-122.477839
9972,180131955,53,18005645,Traffic Collision,2018-01-13,2018-01-13,2018-01-13 13:57:05.000000 UTC,2018-01-13 14:00:06.000000 UTC,2018-01-13 14:13:58.000000 UTC,2018-01-13 14:13:58.000000 UTC,...,1,MEDIC,3,10,9,NaN,"(37.731819888971835, -122.40541209173365)",180131955-53,37.731820,-122.405412
9973,180133046,T03,18005746,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:34:20.000000 UTC,2018-01-13 18:36:16.000000 UTC,2018-01-13 18:37:45.000000 UTC,2018-01-13 18:40:06.000000 UTC,...,1,TRUCK,3,2,6,NaN,"(37.78244403834035, -122.42057454560377)",180133046-T03,37.782444,-122.420575
9974,180130990,RC4,18005555,Medical Incident,2018-01-13,2018-01-13,2018-01-13 09:24:39.000000 UTC,2018-01-13 09:25:14.000000 UTC,2018-01-13 09:27:07.000000 UTC,2018-01-13 09:27:07.000000 UTC,...,1,RESCUE CAPTAIN,1,9,11,NaN,"(37.720457745745186, -122.43703098791046)",180130990-RC4,37.720458,-122.437031
9975,180131726,AM106,18005622,Medical Incident,2018-01-13,2018-01-13,2018-01-13 13:03:23.000000 UTC,2018-01-13 13:04:34.000000 UTC,2018-01-13 13:05:17.000000 UTC,2018-01-13 13:06:12.000000 UTC,...,1,PRIVATE,2,3,6,NaN,"(37.783310406701474, -122.3883798739193)",180131726-AM106,37.783310,-122.388380
9976,180131196,E08,18005577,Medical Incident,2018-01-13,2018-01-13,2018-01-13 10:28:41.000000 UTC,2018-01-13 10:30:14.000000 UTC,2018-01-13 10:30:30.000000 UTC,2018-01-13 10:32:13.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.7748701729732, -122.39441707175159)",180131196-E08,37.774870,-122.394417
9977,180130840,KM08,18005547,Medical Incident,2018-01-13,2018-01-13,2018-01-13 08:28:10.000000 UTC,2018-01-13 08:29:45.000000 UTC,2018-01-13 08:29:58.000000 UTC,2018-01-13 08:30:25.000000 UTC,...,1,PRIVATE,1,1,3,NaN,"(37.80480917127099, -122.4067955298258)",180130840-KM08,37.804809,-122.406796
9978,180131435,E17,18005600,Medical Incident,2018-01-13,2018-01-13,2018-01-13 11:37:39.000000 UTC,2018-01-13 11:38:15.000000 UTC,2018-01-13 11:39:17.000000 UTC,2018-01-13 11:40:33.000000 UTC,...,1,ENGINE,1,10,10,NaN,"(37.71986847521028, -122.39090480126804)",180131435-E17,37.719868,-122.390905
9979,180133469,E21,18005793,Medical Incident,2018-01-13,2018-01-13,2018-01-13 20:33:54.000000 UTC,2018-01-13 20:34:44.000000 UTC,2018-01-13 20:35:08.000000 UTC,2018-01-13 20:36:18.000000 UTC,...,1,ENGINE,1,5,5,NaN,"(37.78116830793363, -122.43480568645582)",180133469-E21,37.781168,-122.434806
9980,180130642,E36,18005530,Structure Fire,2018-01-13,2018-01-12,2018-01-13 06:45:11.000000 UTC,2018-01-13 06:47:35.000000 UTC,2018-01-13 06:47:48.000000 UTC,2018-01-13 06:49:05.000000 UTC,...,1,ENGINE,3,2,9,NaN,"(37.76613438751412, -122.4219350771774)",180130642-E36,37.766134,-122.421935
9981,180133046,65,18005746,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:34:20.000000 UTC,2018-01-13 18:36:16.000000 UTC,2018-01-13 18:37:45.000000 UTC,2018-01-13 18:40:39.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.78244403834035, -122.42057454560377)",180133046-65,37.782444,-122.420575
9982,180130372,AM118,18005479,Traffic Collision,2018-01-13,2018-01-12,2018-01-13 02:52:48.000000 UTC,2018-01-13 02:56:15.000000 UTC,2018-01-13 02:57:03.000000 UTC,2018-01-13 02:58:02.000000 UTC,...,1,PRIVATE,1,None,6,NaN,"(37.810520722520614, -122.36513827228869)",180130372-AM118,37.810521,-122.365138
9983,180131982,KM01,18005647,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:07:21.000000 UTC,2018-01-13 14:07:21.000000 UTC,2018-01-13 14:07:46.000000 UTC,2018-01-13 14:08:18.000000 UTC,...,1,PRIVATE,2,4,2,NaN,"(37.797298027689145, -122.43384673464273)",180131982-KM01,37.797298,-122.433847
9984,180133500,73,18005798,Medical Incident,2018-01-13,2018-01-13,2018-01-13 20:46:37.000000 UTC,2018-01-13 20:46:37.000000 UTC,2018-01-13 20:47:10.000000 UTC,2018-01-13 20:47:18.000000 UTC,...,1,MEDIC,1,2,6,NaN,"(37.77609673484532, -122.4085642977398)",180133500-73,37.776097,-122.408564
9985,180133012,RC3,18005736,Medical Incident,2018-01-13,2018-01-13,2018-01-13 18:29:44.000000 UTC,2018-01-13 18:31:35.000000 UTC,2018-01-13 18:34:37.000000 UTC,2018-01-13 18:34:37.000000 UTC,...,1,RESCUE CAPTAIN,2,10,10,NaN,"(37.7501183410943, -122.39043303882671)",180133012-RC3,37.750118,-122.390433
9986,180132009,E06,18005652,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:14:17.000000 UTC,2018-01-13 14:15:19.000000 UTC,2018-01-13 14:17:00.000000 UTC,2018-01-13 14:18:06.000000 UTC,...,1,ENGINE,3,6,8,NaN,"(37.76063768316806, -122.42584369698614)",180132009-E06,37.760638,-122.425844
9987,180130712,E31,18005537,Medical Incident,2018-01-13,2018-01-12,2018-01-13 07:28:39.000000 UTC,2018-01-13 07:29:26.000000 UTC,2018-01-13 07:29:51.000000 UTC,2018-01-13 07:30:29.000000 UTC,...,1,ENGINE,2,7,1,NaN,"(37.77995613136864, -122.4664265905931)",180130712-E31,37.779956,-122.466427
9988,180131651,95,18005616,Medical Incident,2018-01-13,2018-01-13,2018-01-13 12:41:29.000000 UTC,2018-01-13 12:41:29.000000 UTC,2018-01-13 12:41:41.000000 UTC,2018-01-13 12:41:59.000000 UTC,...,1,MEDIC,1,5,5,NaN,"(37.76815416294501, -122.45431162017093)",180131651-95,37.768154,-122.454312
9989,180131331,60,18005589,Medical Incident,2018-01-13,2018-01-13,2018-01-13 11:09:14.000000 UTC,2018-01-13 11:10:03.000000 UTC,2018-01-13 11:10:26.000000 UTC,2018-01-13 11:10:44.000000 UTC,...,1,MEDIC,2,1,3,NaN,"(37.791834627188145, -122.41081753529559)",180131331-60,37.791835,-122.410818
9990,180130697,E06,18005536,Other,2018-01-13,2018-01-12,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,2018-01-13 07:21:40.000000 UTC,...,1,ENGINE,1,5,8,NaN,"(37.767191551371724, -122.43122179729654)",180130697-E06,37.767192,-122.431222
9991,180130354,70,18005475,Medical Incident,2018-01-13,2018-01-12,2018-01-13 02:44:30.000000 UTC,2018-01-13 02:46:08.000000 UTC,2018-01-13 02:47:17.000000 UTC,2018-01-13 02:47:23.000000 UTC,...,1,MEDIC,1,2,5,NaN,"(37.77588508583154, -122.43036534649241)",180130354-70,37.775885,-122.430365
9992,180134026,E01,18005845,Traffic Collision,2018-01-13,2018-01-13,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,2018-01-13 23:39:49.000000 UTC,...,1,ENGINE,1,2,6,NaN,"(37.77128552595309, -122.41320426710206)",180134026-E01,37.771286,-122.413204
9993,180132041,58,18005657,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:23:06.000000 UTC,2018-01-13 14:23:59.000000 UTC,2018-01-13 14:24:23.000000 UTC,2018-01-13 14:24:30.000000 UTC,...,1,MEDIC,1,2,8,NaN,"(37.761513913312704, -122.42555596887412)",180132041-58,37.761514,-122.425556
9994,180133993,E18,18005843,Medical Incident,2018-01-13,2018-01-13,2018-01-13 23:26:46.000000 UTC,2018-01-13 23:27:44.000000 UTC,2018-01-13 23:28:24.000000 UTC,2018-01-13 23:30:17.000000 UTC,...,1,ENGINE,1,8,4,NaN,"(37.74910205932908, -122.48692720556181)",180133993-E18,37.749102,-122.486927
9995,180130129,E07,18005442,Medical Incident,2018-01-13,2018-01-12,2018-01-13 00:48:33.000000 UTC,2018-01-13 00:48:33.000000 UTC,2018-01-13 00:49:23.000000 UTC,2018-01-13 00:49:42.000000 UTC,...,1,ENGINE,2,6,9,NaN,"(37.75796959799367, -122.41672705336742)",180130129-E07,37.757970,-122.416727
9996,180130999,E38,18005556,Medical Incident,2018-01-13,2018-01-13,2018-01-13 09:26:55.000000 UTC,2018-01-13 09:27:33.000000 UTC,2018-01-13 09:27:50.000000 UTC,2018-01-13 09:29:36.000000 UTC,...,1,ENGINE,1,4,5,NaN,"(37.78708178866631, -122.4258678201407)",180130999-E38,37.787082,-122.425868
9997,180131985,E03,18005648,Medical Incident,2018-01-13,2018-01-13,2018-01-13 14:09:05.000000 UTC,2018-01-13 14:10:04.000000 UTC,2018-01-13 14:12:37.000000 UTC,2018-01-13 14:14:08.000000 UTC,...,1,ENGINE,3,3,6,NaN,"(37.784205674933816, -122.40761273180911)",180131985-E03,37.784206,-122.407613
9998,180132432,RWC2,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:16:14.000000 UTC,...,1,SUPPORT,9,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-RWC2,37.805163,-122.432957
9999,180131803,82,18005629,Medical Incident,2018-01-13,2018-01-13,2018-01-13 13:17:25.000000 UTC,2018-01-13 13:20:29.000000 UTC,2018-01-13 13:20:47.000000 UTC,2018-01-13 13:21:07.000000 UTC,...,1,MEDIC,2,2,6,NaN,"(37.78558247360873, -122.41461720883616)",180131803-82,37.785582,-122.414617

In [20]:
dataFrame = data.sort_values('call_type');
dataFrame

,call_number,unit_id,incident_number,call_type,call_date,watch_date,received_timestamp,entry_timestamp,dispatch_timestamp,response_timestamp,...,number_of_alarms,unit_type,unit_sequence_in_call_dispatch,fire_prevention_district,supervisor_district,neighborhood_district,location,row_id,latitude,longitude
4999,180192032,T03,18008103,Alarms,2018-01-19,2018-01-19,2018-01-19 14:03:11.000000 UTC,2018-01-19 14:04:25.000000 UTC,2018-01-19 14:05:55.000000 UTC,2018-01-19 14:05:55.000000 UTC,...,1,TRUCK,1,1,6,NaN,"(37.78626844171618, -122.41299723589641)",180192032-T03,37.786268,-122.412997
1515,180233758,E03,18009890,Alarms,2018-01-23,2018-01-23,2018-01-23 20:55:52.000000 UTC,2018-01-23 20:57:23.000000 UTC,2018-01-23 20:57:32.000000 UTC,2018-01-23 20:58:42.000000 UTC,...,1,ENGINE,2,2,6,NaN,"(37.78284503447399, -122.41322176673785)",180233758-E03,37.782845,-122.413222
1511,180232178,E18,18009741,Alarms,2018-01-23,2018-01-23,2018-01-23 14:22:49.000000 UTC,2018-01-23 14:24:45.000000 UTC,2018-01-23 14:25:43.000000 UTC,2018-01-23 14:27:28.000000 UTC,...,1,ENGINE,2,8,4,NaN,"(37.73585082965441, -122.50306195980731)",180232178-E18,37.735851,-122.503062
1509,180230921,E08,18009635,Alarms,2018-01-23,2018-01-23,2018-01-23 09:14:17.000000 UTC,2018-01-23 09:15:37.000000 UTC,2018-01-23 09:16:07.000000 UTC,2018-01-23 09:17:13.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.784281616885735, -122.40461464715219)",180230921-E08,37.784282,-122.404615
6063,180174297,B08,18007496,Alarms,2018-01-17,2018-01-17,2018-01-17 23:22:11.000000 UTC,2018-01-17 23:23:55.000000 UTC,2018-01-17 23:24:36.000000 UTC,2018-01-17 23:26:40.000000 UTC,...,1,CHIEF,3,8,4,NaN,"(37.73585082965441, -122.50306195980731)",180174297-B08,37.735851,-122.503062
8407,180143386,E36,18006205,Alarms,2018-01-14,2018-01-14,2018-01-14 21:24:31.000000 UTC,2018-01-14 21:25:59.000000 UTC,2018-01-14 21:26:20.000000 UTC,2018-01-14 21:27:23.000000 UTC,...,1,ENGINE,3,2,5,NaN,"(37.77599354549752, -122.4303873231813)",180143386-E36,37.775994,-122.430387
6059,180172622,T01,18007352,Alarms,2018-01-17,2018-01-17,2018-01-17 15:28:00.000000 UTC,2018-01-17 15:28:56.000000 UTC,2018-01-17 15:29:02.000000 UTC,2018-01-17 15:30:01.000000 UTC,...,1,TRUCK,3,2,6,NaN,"(37.77346648973248, -122.41354690421521)",180172622-T01,37.773466,-122.413547
1500,180231594,T19,18009687,Alarms,2018-01-23,2018-01-23,2018-01-23 11:56:00.000000 UTC,2018-01-23 11:57:25.000000 UTC,2018-01-23 11:57:31.000000 UTC,2018-01-23 11:58:13.000000 UTC,...,1,TRUCK,3,8,7,NaN,"(37.71331778444795, -122.47287586133902)",180231594-T19,37.713318,-122.472876
8413,180141671,E35,18006038,Alarms,2018-01-14,2018-01-14,2018-01-14 13:11:24.000000 UTC,2018-01-14 13:12:47.000000 UTC,2018-01-14 13:13:09.000000 UTC,2018-01-14 13:14:20.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.784321234941714, -122.38904057367033)",180141671-E35,37.784321,-122.389041
8419,180140730,B03,18005936,Alarms,2018-01-14,2018-01-14,2018-01-14 08:06:37.000000 UTC,2018-01-14 08:07:26.000000 UTC,2018-01-14 08:07:35.000000 UTC,2018-01-14 08:08:51.000000 UTC,...,1,CHIEF,2,3,6,NaN,"(37.79047503616445, -122.39055604599017)",180140730-B03,37.790475,-122.390556
6077,180173391,E01,18007409,Alarms,2018-01-17,2018-01-17,2018-01-17 18:13:42.000000 UTC,2018-01-17 18:15:30.000000 UTC,2018-01-17 18:15:34.000000 UTC,2018-01-17 18:16:47.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.78378929692922, -122.40926630730081)",180173391-E01,37.783789,-122.409266
3753,180201035,B03,18008440,Alarms,2018-01-20,2018-01-20,2018-01-20 09:27:58.000000 UTC,2018-01-20 09:29:25.000000 UTC,2018-01-20 09:29:43.000000 UTC,2018-01-20 09:31:35.000000 UTC,...,1,CHIEF,2,3,6,NaN,"(37.78782466943738, -122.39703243652791)",180201035-B03,37.787825,-122.397032
6043,180170058,E44,18007124,Alarms,2018-01-17,2018-01-16,2018-01-17 00:28:21.000000 UTC,2018-01-17 00:32:36.000000 UTC,2018-01-17 00:32:42.000000 UTC,2018-01-17 00:35:01.000000 UTC,...,1,ENGINE,1,10,10,NaN,"(37.71076469005101, -122.39079280516823)",180170058-E44,37.710765,-122.390793
8435,180141510,T07,18006015,Alarms,2018-01-14,2018-01-14,2018-01-14 12:22:33.000000 UTC,2018-01-14 12:23:38.000000 UTC,2018-01-14 12:24:01.000000 UTC,2018-01-14 12:26:37.000000 UTC,...,1,TRUCK,2,6,9,NaN,"(37.75809277464886, -122.41468474542069)",180141510-T07,37.758093,-122.414685
1480,180231783,T03,18009705,Alarms,2018-01-23,2018-01-23,2018-01-23 12:40:47.000000 UTC,2018-01-23 12:42:49.000000 UTC,2018-01-23 12:42:57.000000 UTC,2018-01-23 12:44:46.000000 UTC,...,1,TRUCK,1,4,3,NaN,"(37.788635275240495, -122.41699034261856)",180231783-T03,37.788635,-122.416990
1474,180232991,B05,18009819,Alarms,2018-01-23,2018-01-23,2018-01-23 17:34:02.000000 UTC,2018-01-23 17:36:25.000000 UTC,2018-01-23 17:37:35.000000 UTC,2018-01-23 17:37:35.000000 UTC,...,1,CHIEF,1,5,5,NaN,"(37.773882777538766, -122.44272817015577)",180232991-B05,37.773883,-122.442728
8443,180140508,T04,18005913,Alarms,2018-01-14,2018-01-13,2018-01-14 05:03:00.000000 UTC,2018-01-14 05:05:09.000000 UTC,2018-01-14 05:05:16.000000 UTC,2018-01-14 05:07:16.000000 UTC,...,1,TRUCK,2,3,10,NaN,"(37.76362722874533, -122.38972338997317)",180140508-T04,37.763627,-122.389723
1462,180232353,E13,18009761,Alarms,2018-01-23,2018-01-23,2018-01-23 15:16:10.000000 UTC,2018-01-23 15:17:32.000000 UTC,2018-01-23 15:17:57.000000 UTC,2018-01-23 15:18:49.000000 UTC,...,1,ENGINE,1,3,6,NaN,"(37.79188538627328, -122.3933412235165)",180232353-E13,37.791885,-122.393341
8453,180143511,T17,18006222,Alarms,2018-01-14,2018-01-14,2018-01-14 21:57:57.000000 UTC,2018-01-14 22:00:39.000000 UTC,2018-01-14 22:01:03.000000 UTC,2018-01-14 22:02:10.000000 UTC,...,1,TRUCK,2,10,10,NaN,"(37.72881556768414, -122.3803270134155)",180143511-T17,37.728816,-122.380327
1459,180232383,83,18009766,Alarms,2018-01-23,2018-01-23,2018-01-23 15:21:51.000000 UTC,2018-01-23 15:26:20.000000 UTC,2018-01-23 15:28:25.000000 UTC,2018-01-23 15:28:32.000000 UTC,...,1,MEDIC,4,9,10,NaN,"(37.71064899317439, -122.41246880128023)",180232383-83,37.710649,-122.412469
1456,180231783,E03,18009705,Alarms,2018-01-23,2018-01-23,2018-01-23 12:40:47.000000 UTC,2018-01-23 12:42:49.000000 UTC,2018-01-23 12:42:57.000000 UTC,2018-01-23 12:44:02.000000 UTC,...,1,ENGINE,2,4,3,NaN,"(37.788635275240495, -122.41699034261856)",180231783-E03,37.788635,-122.416990
1486,180233481,T08,18009865,Alarms,2018-01-23,2018-01-23,2018-01-23 19:27:16.000000 UTC,2018-01-23 19:28:24.000000 UTC,2018-01-23 19:28:46.000000 UTC,2018-01-23 19:30:13.000000 UTC,...,1,TRUCK,3,2,10,NaN,"(37.76795762631065, -122.40374766147274)",180233481-T08,37.767958,-122.403748
3778,180200758,E44,18008407,Alarms,2018-01-20,2018-01-19,2018-01-20 07:46:46.000000 UTC,2018-01-20 07:49:31.000000 UTC,2018-01-20 07:49:44.000000 UTC,2018-01-20 07:50:44.000000 UTC,...,1,ENGINE,3,10,10,NaN,"(37.718722285677096, -122.38911832496534)",180200758-E44,37.718722,-122.389118
6079,180173886,B04,18007460,Alarms,2018-01-17,2018-01-17,2018-01-17 20:46:23.000000 UTC,2018-01-17 20:48:19.000000 UTC,2018-01-17 20:49:16.000000 UTC,2018-01-17 20:50:15.000000 UTC,...,1,CHIEF,2,4,2,NaN,"(37.79256246987408, -122.44048841448321)",180173886-B04,37.792562,-122.440488
8378,180152787,B01,18006570,Alarms,2018-01-15,2018-01-15,2018-01-15 18:04:59.000000 UTC,2018-01-15 18:06:08.000000 UTC,2018-01-15 18:06:29.000000 UTC,2018-01-15 18:07:50.000000 UTC,...,1,CHIEF,3,1,3,NaN,"(37.78876832856105, -122.40843000617386)",180152787-B01,37.788768,-122.408430
8306,180152544,B05,18006546,Alarms,2018-01-15,2018-01-15,2018-01-15 16:53:47.000000 UTC,2018-01-15 16:55:26.000000 UTC,2018-01-15 16:55:54.000000 UTC,2018-01-15 16:57:56.000000 UTC,...,1,CHIEF,3,2,6,NaN,"(37.776269506616586, -122.41725760506962)",180152544-B05,37.776270,-122.417258
8313,180151165,T02,18006403,Alarms,2018-01-15,2018-01-15,2018-01-15 10:45:04.000000 UTC,2018-01-15 10:46:28.000000 UTC,2018-01-15 10:47:19.000000 UTC,2018-01-15 10:49:18.000000 UTC,...,1,TRUCK,2,1,3,NaN,"(37.7914523626926, -122.4065433000874)",180151165-T02,37.791452,-122.406543
1589,180231594,B09,18009687,Alarms,2018-01-23,2018-01-23,2018-01-23 11:56:00.000000 UTC,2018-01-23 11:57:25.000000 UTC,2018-01-23 11:57:31.000000 UTC,2018-01-23 11:58:51.000000 UTC,...,1,CHIEF,2,8,7,NaN,"(37.71331778444795, -122.47287586133902)",180231594-B09,37.713318,-122.472876
3678,180203618,T01,18008707,Alarms,2018-01-20,2018-01-20,2018-01-20 22:34:25.000000 UTC,2018-01-20 22:36:10.000000 UTC,2018-01-20 22:36:24.000000 UTC,2018-01-20 22:38:39.000000 UTC,...,1,TRUCK,2,3,6,NaN,"(37.78316766387155, -122.39782549526826)",180203618-T01,37.783168,-122.397825
8320,180150219,E07,18006282,Alarms,2018-01-15,2018-01-14,2018-01-15 02:00:02.000000 UTC,2018-01-15 02:02:20.000000 UTC,2018-01-15 02:03:02.000000 UTC,2018-01-15 02:06:43.000000 UTC,...,1,ENGINE,1,6,9,NaN,"(37.75271253709323, -122.40959291210274)",180150219-E07,37.752713,-122.409593
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4697,180192988,RS1,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:37:57.000000 UTC,...,1,RESCUE SQUAD,10,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-RS1,37.791525,-122.483480
2679,180211077,KM01,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:23:33.000000 UTC,...,1,PRIVATE,6,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-KM01,37.798045,-122.396367
4928,180192988,RWC2,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:39:18.000000 UTC,...,1,SUPPORT,7,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-RWC2,37.791525,-122.483480
7558,180151089,E19,18006392,Water Rescue,2018-01-15,2018-01-15,2018-01-15 10:20:59.000000 UTC,2018-01-15 10:22:27.000000 UTC,2018-01-15 10:23:16.000000 UTC,2018-01-15 10:23:40.000000 UTC,...,1,ENGINE,5,8,7,NaN,"(37.722078288127044, -122.5017208227219)",180151089-E19,37.722078,-122.501721
3105,180211077,RC1,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:22:58.000000 UTC,...,1,RESCUE CAPTAIN,1,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-RC1,37.798045,-122.396367
4835,180192988,KM02,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:38:13.000000 UTC,...,1,PRIVATE,3,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-KM02,37.791525,-122.483480
9929,180132726,T14,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:22:57.000000 UTC,2018-01-13 17:25:10.000000 UTC,...,1,TRUCK,4,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-T14,37.791525,-122.483480
3043,180211077,T13,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:24:29.000000 UTC,...,1,TRUCK,2,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-T13,37.798045,-122.396367
9604,180132726,RC2,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:22:57.000000 UTC,2018-01-13 17:24:53.000000 UTC,...,1,RESCUE CAPTAIN,3,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-RC2,37.791525,-122.483480
3168,180211077,T16,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:24:53.000000 UTC,...,1,TRUCK,11,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-T16,37.798045,-122.396367
7809,180151089,B08,18006392,Water Rescue,2018-01-15,2018-01-15,2018-01-15 10:20:59.000000 UTC,2018-01-15 10:22:27.000000 UTC,2018-01-15 10:23:16.000000 UTC,2018-01-15 10:24:10.000000 UTC,...,1,CHIEF,2,8,7,NaN,"(37.722078288127044, -122.5017208227219)",180151089-B08,37.722078,-122.501721
2887,180211077,E02,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:24:52.000000 UTC,...,1,ENGINE,5,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-E02,37.798045,-122.396367
9412,180132726,E14,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:22:57.000000 UTC,2018-01-13 17:24:11.000000 UTC,...,1,ENGINE,1,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-E14,37.791525,-122.483480
9820,180132726,SR34,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:57:50.000000 UTC,2018-01-13 17:57:50.000000 UTC,...,1,SUPPORT,9,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-SR34,37.791525,-122.483480
7883,180151089,RS2,18006392,Water Rescue,2018-01-15,2018-01-15,2018-01-15 10:20:59.000000 UTC,2018-01-15 10:22:27.000000 UTC,2018-01-15 10:23:16.000000 UTC,2018-01-15 10:25:32.000000 UTC,...,1,RESCUE SQUAD,7,8,7,NaN,"(37.722078288127044, -122.5017208227219)",180151089-RS2,37.722078,-122.501721
4793,180192988,B07,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:38:10.000000 UTC,...,1,CHIEF,1,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-B07,37.791525,-122.483480
9858,180132726,CR14,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:22:57.000000 UTC,2018-01-13 17:25:53.000000 UTC,...,1,SUPPORT,8,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-CR14,37.791525,-122.483480
2867,180211077,FB1,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:24:36.000000 UTC,...,1,SUPPORT,9,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-FB1,37.798045,-122.396367
7675,180151089,95,18006392,Water Rescue,2018-01-15,2018-01-15,2018-01-15 10:20:59.000000 UTC,2018-01-15 10:22:27.000000 UTC,2018-01-15 10:23:16.000000 UTC,2018-01-15 10:23:52.000000 UTC,...,1,MEDIC,3,8,7,NaN,"(37.722078288127044, -122.5017208227219)",180151089-95,37.722078,-122.501721
4974,180192988,E14,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:38:27.000000 UTC,...,1,ENGINE,2,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-E14,37.791525,-122.483480
9615,180132432,RS1,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:15:48.000000 UTC,...,1,RESCUE SQUAD,13,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-RS1,37.805163,-122.432957
7673,180151089,SR18,18006392,Water Rescue,2018-01-15,2018-01-15,2018-01-15 10:20:59.000000 UTC,2018-01-15 10:22:27.000000 UTC,2018-01-15 10:34:47.000000 UTC,2018-01-15 10:38:33.000000 UTC,...,1,SUPPORT,9,8,7,NaN,"(37.722078288127044, -122.5017208227219)",180151089-SR18,37.722078,-122.501721
9840,180132432,RC1,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:16:07.000000 UTC,...,1,RESCUE CAPTAIN,3,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-RC1,37.805163,-122.432957
2860,180211077,E13,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:26:58.000000 UTC,2018-01-21 10:26:58.000000 UTC,...,1,ENGINE,7,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-E13,37.798045,-122.396367
2531,180211077,RWC1,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:25:24.000000 UTC,...,1,SUPPORT,12,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-RWC1,37.798045,-122.396367
3071,180211077,RS1,18008874,Water Rescue,2018-01-21,2018-01-21,2018-01-21 10:19:35.000000 UTC,2018-01-21 10:21:28.000000 UTC,2018-01-21 10:22:45.000000 UTC,2018-01-21 10:24:45.000000 UTC,...,1,RESCUE SQUAD,3,1,3,NaN,"(37.7980449492818, -122.3963670843851)",180211077-RS1,37.798045,-122.396367
9965,180132726,RS1,18005714,Water Rescue,2018-01-13,2018-01-13,2018-01-13 17:19:47.000000 UTC,2018-01-13 17:22:11.000000 UTC,2018-01-13 17:22:57.000000 UTC,2018-01-13 17:24:54.000000 UTC,...,1,RESCUE SQUAD,6,7,2,NaN,"(37.7915253713789, -122.483480228628)",180132726-RS1,37.791525,-122.483480
9237,180132432,T16,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:15:46.000000 UTC,...,1,TRUCK,10,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-T16,37.805163,-122.432957
9218,180132432,FB1,18005695,Water Rescue,2018-01-13,2018-01-13,2018-01-13 16:12:05.000000 UTC,2018-01-13 16:14:19.000000 UTC,2018-01-13 16:14:57.000000 UTC,2018-01-13 16:16:01.000000 UTC,...,1,SUPPORT,12,4,2,NaN,"(37.80516256556238, -122.43295744051808)",180132432-FB1,37.805163,-122.432957
4754,180192988,T14,18008183,Water Rescue,2018-01-19,2018-01-19,2018-01-19 17:31:53.000000 UTC,2018-01-19 17:35:31.000000 UTC,2018-01-19 17:36:59.000000 UTC,2018-01-19 17:38:47.000000 UTC,...,1,TRUCK,4,7,2,NaN,"(37.7915253713789, -122.483480228628)",180192988-T14,37.791525,-122.483480

In [46]:
typeContents = []
typeContents = dataFrame.call_type.value_counts();

Medical Incident                   6791
Alarms                             1061
Structure Fire                     1029
Traffic Collision                   410
Outside Fire                        144
Other                               129
Citizen Assist / Service Call       114
Gas Leak (Natural and LP Gases)      86
Train / Rail Incident                55
Water Rescue                         54
Vehicle Fire                         45
Elevator / Escalator Rescue          23
Electrical Hazard                    21
Smoke Investigation (Outside)        15
Odor (Strange / Unknown)             10
Fuel Spill                           10
HazMat                                3
Name: call_type, dtype: int64

In [1]:
typeContents.to_csv('TypeContents.csv')

NameError: name 'typeContents' is not defined

In [2]:
mapData = data[['call_type','latitude','longitude']]

NameError: name 'data' is not defined

In [54]:
mapData.to_csv('MapData.csv')

In [4]:
import pandas as pd
import numpy as np

In [7]:
mapdata = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/MapData.csv')
mapdata

      Unnamed: 0          call_type   latitude   longitude
0              0   Medical Incident  37.774442 -122.504679
1              1   Medical Incident  37.774095 -122.420001
2              2   Medical Incident  37.755218 -122.475540
3              3             Alarms  37.790319 -122.423163
4              4             Alarms  37.777328 -122.393089
5              5             Alarms  37.756890 -122.422229
6              6     Structure Fire  37.783359 -122.416695
7              7  Traffic Collision  37.769244 -122.408007
8              8             Alarms  37.807120 -122.416428
9              9   Medical Incident  37.712150 -122.417141
10            10   Medical Incident  37.778832 -122.415642
11            11   Medical Incident  37.797092 -122.398333
12            12   Medical Incident  37.756096 -122.427783
13            13   Medical Incident  37.780792 -122.408386
14            14   Medical Incident  37.752239 -122.418445
15            15     Structure Fire  37.785217 -122.417070
16            16   Medical Incident  37.779523 -122.412639
17            17   Medical Incident  37.748173 -122.458695
18            18   Medical Incident  37.770055 -122.446128
19            19     Structure Fire  37.783359 -122.416695
20            20   Medical Incident  37.777790 -122.412834
21            21   Medical Incident  37.780669 -122.401678
22            22   Medical Incident  37.774093 -122.441084
23            23   Medical Incident  37.802828 -122.413034
24            24   Medical Incident  37.786268 -122.412997
25            25   Medical Incident  37.770273 -122.448605
26            26   Medical Incident  37.781914 -122.413032
27            27              Other  37.722298 -122.411303
28            28   Medical Incident  37.759628 -122.415923
29            29   Medical Incident  37.781865 -122.414285
...          ...                ...        ...         ...
9970        9970   Medical Incident  37.761777 -122.435152
9971        9971   Medical Incident  37.742020 -122.477839
9972        9972  Traffic Collision  37.731820 -122.405412
9973        9973   Medical Incident  37.782444 -122.420575
9974        9974   Medical Incident  37.720458 -122.437031
9975        9975   Medical Incident  37.783310 -122.388380
9976        9976   Medical Incident  37.774870 -122.394417
9977        9977   Medical Incident  37.804809 -122.406796
9978        9978   Medical Incident  37.719868 -122.390905
9979        9979   Medical Incident  37.781168 -122.434806
9980        9980     Structure Fire  37.766134 -122.421935
9981        9981   Medical Incident  37.782444 -122.420575
9982        9982  Traffic Collision  37.810521 -122.365138
9983        9983   Medical Incident  37.797298 -122.433847
9984        9984   Medical Incident  37.776097 -122.408564
9985        9985   Medical Incident  37.750118 -122.390433
9986        9986   Medical Incident  37.760638 -122.425844
9987        9987   Medical Incident  37.779956 -122.466427
9988        9988   Medical Incident  37.768154 -122.454312
9989        9989   Medical Incident  37.791835 -122.410818
9990        9990              Other  37.767192 -122.431222
9991        9991   Medical Incident  37.775885 -122.430365
9992        9992  Traffic Collision  37.771286 -122.413204
9993        9993   Medical Incident  37.761514 -122.425556
9994        9994   Medical Incident  37.749102 -122.486927
9995        9995   Medical Incident  37.757970 -122.416727
9996        9996   Medical Incident  37.787082 -122.425868
9997        9997   Medical Incident  37.784206 -122.407613
9998        9998       Water Rescue  37.805163 -122.432957
9999        9999   Medical Incident  37.785582 -122.414617

[10000 rows x 4 columns]

In [10]:
updatemapdata = mapdata[(mapdata.call_type == 'Medical Incident') | (mapdata.call_type == 'Alarms') |(mapdata.call_type == 'Structure Fire')]

In [11]:
updatemapdata

      Unnamed: 0         call_type   latitude   longitude
0              0  Medical Incident  37.774442 -122.504679
1              1  Medical Incident  37.774095 -122.420001
2              2  Medical Incident  37.755218 -122.475540
3              3            Alarms  37.790319 -122.423163
4              4            Alarms  37.777328 -122.393089
5              5            Alarms  37.756890 -122.422229
6              6    Structure Fire  37.783359 -122.416695
8              8            Alarms  37.807120 -122.416428
9              9  Medical Incident  37.712150 -122.417141
10            10  Medical Incident  37.778832 -122.415642
11            11  Medical Incident  37.797092 -122.398333
12            12  Medical Incident  37.756096 -122.427783
13            13  Medical Incident  37.780792 -122.408386
14            14  Medical Incident  37.752239 -122.418445
15            15    Structure Fire  37.785217 -122.417070
16            16  Medical Incident  37.779523 -122.412639
17            17  Medical Incident  37.748173 -122.458695
18            18  Medical Incident  37.770055 -122.446128
19            19    Structure Fire  37.783359 -122.416695
20            20  Medical Incident  37.777790 -122.412834
21            21  Medical Incident  37.780669 -122.401678
22            22  Medical Incident  37.774093 -122.441084
23            23  Medical Incident  37.802828 -122.413034
24            24  Medical Incident  37.786268 -122.412997
25            25  Medical Incident  37.770273 -122.448605
26            26  Medical Incident  37.781914 -122.413032
28            28  Medical Incident  37.759628 -122.415923
29            29  Medical Incident  37.781865 -122.414285
30            30  Medical Incident  37.779383 -122.418484
31            31  Medical Incident  37.791546 -122.420037
...          ...               ...        ...         ...
9963        9963            Alarms  37.793488 -122.398206
9964        9964    Structure Fire  37.786268 -122.412997
9966        9966    Structure Fire  37.776464 -122.426263
9967        9967    Structure Fire  37.766134 -122.421935
9968        9968  Medical Incident  37.760085 -122.434996
9970        9970  Medical Incident  37.761777 -122.435152
9971        9971  Medical Incident  37.742020 -122.477839
9973        9973  Medical Incident  37.782444 -122.420575
9974        9974  Medical Incident  37.720458 -122.437031
9975        9975  Medical Incident  37.783310 -122.388380
9976        9976  Medical Incident  37.774870 -122.394417
9977        9977  Medical Incident  37.804809 -122.406796
9978        9978  Medical Incident  37.719868 -122.390905
9979        9979  Medical Incident  37.781168 -122.434806
9980        9980    Structure Fire  37.766134 -122.421935
9981        9981  Medical Incident  37.782444 -122.420575
9983        9983  Medical Incident  37.797298 -122.433847
9984        9984  Medical Incident  37.776097 -122.408564
9985        9985  Medical Incident  37.750118 -122.390433
9986        9986  Medical Incident  37.760638 -122.425844
9987        9987  Medical Incident  37.779956 -122.466427
9988        9988  Medical Incident  37.768154 -122.454312
9989        9989  Medical Incident  37.791835 -122.410818
9991        9991  Medical Incident  37.775885 -122.430365
9993        9993  Medical Incident  37.761514 -122.425556
9994        9994  Medical Incident  37.749102 -122.486927
9995        9995  Medical Incident  37.757970 -122.416727
9996        9996  Medical Incident  37.787082 -122.425868
9997        9997  Medical Incident  37.784206 -122.407613
9999        9999  Medical Incident  37.785582 -122.414617

[8881 rows x 4 columns]

In [23]:
updatemapdata.insert(4,'marker-color', len(updatemapdata))

ValueError: cannot insert marker-color, already exists

In [21]:
updatemapdata

      Unnamed: 0         call_type   latitude   longitude  marker-color
0              0  Medical Incident  37.774442 -122.504679          8881
1              1  Medical Incident  37.774095 -122.420001          8881
2              2  Medical Incident  37.755218 -122.475540          8881
3              3            Alarms  37.790319 -122.423163          8881
4              4            Alarms  37.777328 -122.393089          8881
5              5            Alarms  37.756890 -122.422229          8881
6              6    Structure Fire  37.783359 -122.416695          8881
8              8            Alarms  37.807120 -122.416428          8881
9              9  Medical Incident  37.712150 -122.417141          8881
10            10  Medical Incident  37.778832 -122.415642          8881
11            11  Medical Incident  37.797092 -122.398333          8881
12            12  Medical Incident  37.756096 -122.427783          8881
13            13  Medical Incident  37.780792 -122.408386          8881
14            14  Medical Incident  37.752239 -122.418445          8881
15            15    Structure Fire  37.785217 -122.417070          8881
16            16  Medical Incident  37.779523 -122.412639          8881
17            17  Medical Incident  37.748173 -122.458695          8881
18            18  Medical Incident  37.770055 -122.446128          8881
19            19    Structure Fire  37.783359 -122.416695          8881
20            20  Medical Incident  37.777790 -122.412834          8881
21            21  Medical Incident  37.780669 -122.401678          8881
22            22  Medical Incident  37.774093 -122.441084          8881
23            23  Medical Incident  37.802828 -122.413034          8881
24            24  Medical Incident  37.786268 -122.412997          8881
25            25  Medical Incident  37.770273 -122.448605          8881
26            26  Medical Incident  37.781914 -122.413032          8881
28            28  Medical Incident  37.759628 -122.415923          8881
29            29  Medical Incident  37.781865 -122.414285          8881
30            30  Medical Incident  37.779383 -122.418484          8881
31            31  Medical Incident  37.791546 -122.420037          8881
...          ...               ...        ...         ...           ...
9963        9963            Alarms  37.793488 -122.398206          8881
9964        9964    Structure Fire  37.786268 -122.412997          8881
9966        9966    Structure Fire  37.776464 -122.426263          8881
9967        9967    Structure Fire  37.766134 -122.421935          8881
9968        9968  Medical Incident  37.760085 -122.434996          8881
9970        9970  Medical Incident  37.761777 -122.435152          8881
9971        9971  Medical Incident  37.742020 -122.477839          8881
9973        9973  Medical Incident  37.782444 -122.420575          8881
9974        9974  Medical Incident  37.720458 -122.437031          8881
9975        9975  Medical Incident  37.783310 -122.388380          8881
9976        9976  Medical Incident  37.774870 -122.394417          8881
9977        9977  Medical Incident  37.804809 -122.406796          8881
9978        9978  Medical Incident  37.719868 -122.390905          8881
9979        9979  Medical Incident  37.781168 -122.434806          8881
9980        9980    Structure Fire  37.766134 -122.421935          8881
9981        9981  Medical Incident  37.782444 -122.420575          8881
9983        9983  Medical Incident  37.797298 -122.433847          8881
9984        9984  Medical Incident  37.776097 -122.408564          8881
9985        9985  Medical Incident  37.750118 -122.390433          8881
9986        9986  Medical Incident  37.760638 -122.425844          8881
9987        9987  Medical Incident  37.779956 -122.466427          8881
9988        9988  Medical Incident  37.768154 -122.454312          8881
9989        9989  Medical Incident  37.791835 -122.410818          8881
9991        9991  Medical Incident  37.775885 -122.430365          8881
9993        9993  Medical Incident  37.761514 -122.425556          8881
9994        9994  Medical Incident  37.749102 -122.486927          8881
9995        9995  Medical Incident  37.757970 -122.416727          8881
9996        9996  Medical Incident  37.787082 -122.425868          8881
9997        9997  Medical Incident  37.784206 -122.407613          8881
9999        9999  Medical Incident  37.785582 -122.414617          8881

[8881 rows x 5 columns]

In [25]:
del updatemapdata['marker-color']
updatemapdata

      Unnamed: 0         call_type   latitude   longitude
0              0  Medical Incident  37.774442 -122.504679
1              1  Medical Incident  37.774095 -122.420001
2              2  Medical Incident  37.755218 -122.475540
3              3            Alarms  37.790319 -122.423163
4              4            Alarms  37.777328 -122.393089
5              5            Alarms  37.756890 -122.422229
6              6    Structure Fire  37.783359 -122.416695
8              8            Alarms  37.807120 -122.416428
9              9  Medical Incident  37.712150 -122.417141
10            10  Medical Incident  37.778832 -122.415642
11            11  Medical Incident  37.797092 -122.398333
12            12  Medical Incident  37.756096 -122.427783
13            13  Medical Incident  37.780792 -122.408386
14            14  Medical Incident  37.752239 -122.418445
15            15    Structure Fire  37.785217 -122.417070
16            16  Medical Incident  37.779523 -122.412639
17            17  Medical Incident  37.748173 -122.458695
18            18  Medical Incident  37.770055 -122.446128
19            19    Structure Fire  37.783359 -122.416695
20            20  Medical Incident  37.777790 -122.412834
21            21  Medical Incident  37.780669 -122.401678
22            22  Medical Incident  37.774093 -122.441084
23            23  Medical Incident  37.802828 -122.413034
24            24  Medical Incident  37.786268 -122.412997
25            25  Medical Incident  37.770273 -122.448605
26            26  Medical Incident  37.781914 -122.413032
28            28  Medical Incident  37.759628 -122.415923
29            29  Medical Incident  37.781865 -122.414285
30            30  Medical Incident  37.779383 -122.418484
31            31  Medical Incident  37.791546 -122.420037
...          ...               ...        ...         ...
9963        9963            Alarms  37.793488 -122.398206
9964        9964    Structure Fire  37.786268 -122.412997
9966        9966    Structure Fire  37.776464 -122.426263
9967        9967    Structure Fire  37.766134 -122.421935
9968        9968  Medical Incident  37.760085 -122.434996
9970        9970  Medical Incident  37.761777 -122.435152
9971        9971  Medical Incident  37.742020 -122.477839
9973        9973  Medical Incident  37.782444 -122.420575
9974        9974  Medical Incident  37.720458 -122.437031
9975        9975  Medical Incident  37.783310 -122.388380
9976        9976  Medical Incident  37.774870 -122.394417
9977        9977  Medical Incident  37.804809 -122.406796
9978        9978  Medical Incident  37.719868 -122.390905
9979        9979  Medical Incident  37.781168 -122.434806
9980        9980    Structure Fire  37.766134 -122.421935
9981        9981  Medical Incident  37.782444 -122.420575
9983        9983  Medical Incident  37.797298 -122.433847
9984        9984  Medical Incident  37.776097 -122.408564
9985        9985  Medical Incident  37.750118 -122.390433
9986        9986  Medical Incident  37.760638 -122.425844
9987        9987  Medical Incident  37.779956 -122.466427
9988        9988  Medical Incident  37.768154 -122.454312
9989        9989  Medical Incident  37.791835 -122.410818
9991        9991  Medical Incident  37.775885 -122.430365
9993        9993  Medical Incident  37.761514 -122.425556
9994        9994  Medical Incident  37.749102 -122.486927
9995        9995  Medical Incident  37.757970 -122.416727
9996        9996  Medical Incident  37.787082 -122.425868
9997        9997  Medical Incident  37.784206 -122.407613
9999        9999  Medical Incident  37.785582 -122.414617

[8881 rows x 4 columns]

In [33]:
marker = []
for row in updatemapdata['call_type']:
    if (updatemapdata.isin*'Medical Incident'):
        marker.append('#ff0000')
    elif (updatemapdata.isin('Alarms'):
        marker.append('#0000ff')
    elif (updatemapdata.isin('Structure Fire'):
        marker.append('#ffffff')
    else: 
        marker.append('0')

updatamapdata['marker-color'] = marker

SyntaxError: invalid syntax (<ipython-input-33-8721bc9034f2>, line 5)

In [45]:
data = pd.read_csv('/Users/navneethbabra/Documents/Cap 1/sfpd-dispatch/sfpd_dispatch_data_subset.csv');
mapData = data[['call_type','latitude', 'longitude']]
mapData

              call_type   latitude   longitude
0      Medical Incident  37.774442 -122.504679
1      Medical Incident  37.774095 -122.420001
2      Medical Incident  37.755218 -122.475540
3                Alarms  37.790319 -122.423163
4                Alarms  37.777328 -122.393089
5                Alarms  37.756890 -122.422229
6        Structure Fire  37.783359 -122.416695
7     Traffic Collision  37.769244 -122.408007
8                Alarms  37.807120 -122.416428
9      Medical Incident  37.712150 -122.417141
10     Medical Incident  37.778832 -122.415642
11     Medical Incident  37.797092 -122.398333
12     Medical Incident  37.756096 -122.427783
13     Medical Incident  37.780792 -122.408386
14     Medical Incident  37.752239 -122.418445
15       Structure Fire  37.785217 -122.417070
16     Medical Incident  37.779523 -122.412639
17     Medical Incident  37.748173 -122.458695
18     Medical Incident  37.770055 -122.446128
19       Structure Fire  37.783359 -122.416695
20     Medical Incident  37.777790 -122.412834
21     Medical Incident  37.780669 -122.401678
22     Medical Incident  37.774093 -122.441084
23     Medical Incident  37.802828 -122.413034
24     Medical Incident  37.786268 -122.412997
25     Medical Incident  37.770273 -122.448605
26     Medical Incident  37.781914 -122.413032
27                Other  37.722298 -122.411303
28     Medical Incident  37.759628 -122.415923
29     Medical Incident  37.781865 -122.414285
...                 ...        ...         ...
9970   Medical Incident  37.761777 -122.435152
9971   Medical Incident  37.742020 -122.477839
9972  Traffic Collision  37.731820 -122.405412
9973   Medical Incident  37.782444 -122.420575
9974   Medical Incident  37.720458 -122.437031
9975   Medical Incident  37.783310 -122.388380
9976   Medical Incident  37.774870 -122.394417
9977   Medical Incident  37.804809 -122.406796
9978   Medical Incident  37.719868 -122.390905
9979   Medical Incident  37.781168 -122.434806
9980     Structure Fire  37.766134 -122.421935
9981   Medical Incident  37.782444 -122.420575
9982  Traffic Collision  37.810521 -122.365138
9983   Medical Incident  37.797298 -122.433847
9984   Medical Incident  37.776097 -122.408564
9985   Medical Incident  37.750118 -122.390433
9986   Medical Incident  37.760638 -122.425844
9987   Medical Incident  37.779956 -122.466427
9988   Medical Incident  37.768154 -122.454312
9989   Medical Incident  37.791835 -122.410818
9990              Other  37.767192 -122.431222
9991   Medical Incident  37.775885 -122.430365
9992  Traffic Collision  37.771286 -122.413204
9993   Medical Incident  37.761514 -122.425556
9994   Medical Incident  37.749102 -122.486927
9995   Medical Incident  37.757970 -122.416727
9996   Medical Incident  37.787082 -122.425868
9997   Medical Incident  37.784206 -122.407613
9998       Water Rescue  37.805163 -122.432957
9999   Medical Incident  37.785582 -122.414617

[10000 rows x 3 columns]

In [37]:
mapData.to_csv('MapData.csv')

In [50]:
a = mapData[mapData.call_type == 'Medical Incident']
a

             call_type   latitude   longitude
0     Medical Incident  37.774442 -122.504679
1     Medical Incident  37.774095 -122.420001
2     Medical Incident  37.755218 -122.475540
9     Medical Incident  37.712150 -122.417141
10    Medical Incident  37.778832 -122.415642
11    Medical Incident  37.797092 -122.398333
12    Medical Incident  37.756096 -122.427783
13    Medical Incident  37.780792 -122.408386
14    Medical Incident  37.752239 -122.418445
16    Medical Incident  37.779523 -122.412639
17    Medical Incident  37.748173 -122.458695
18    Medical Incident  37.770055 -122.446128
20    Medical Incident  37.777790 -122.412834
21    Medical Incident  37.780669 -122.401678
22    Medical Incident  37.774093 -122.441084
23    Medical Incident  37.802828 -122.413034
24    Medical Incident  37.786268 -122.412997
25    Medical Incident  37.770273 -122.448605
26    Medical Incident  37.781914 -122.413032
28    Medical Incident  37.759628 -122.415923
29    Medical Incident  37.781865 -122.414285
30    Medical Incident  37.779383 -122.418484
31    Medical Incident  37.791546 -122.420037
33    Medical Incident  37.773190 -122.418237
34    Medical Incident  37.720947 -122.453165
35    Medical Incident  37.784978 -122.459698
36    Medical Incident  37.788945 -122.426252
37    Medical Incident  37.742261 -122.421965
38    Medical Incident  37.785744 -122.405831
39    Medical Incident  37.783260 -122.418366
...                ...        ...         ...
9955  Medical Incident  37.799843 -122.436046
9956  Medical Incident  37.737956 -122.421913
9959  Medical Incident  37.766545 -122.395061
9961  Medical Incident  37.761514 -122.425556
9962  Medical Incident  37.796335 -122.400515
9968  Medical Incident  37.760085 -122.434996
9970  Medical Incident  37.761777 -122.435152
9971  Medical Incident  37.742020 -122.477839
9973  Medical Incident  37.782444 -122.420575
9974  Medical Incident  37.720458 -122.437031
9975  Medical Incident  37.783310 -122.388380
9976  Medical Incident  37.774870 -122.394417
9977  Medical Incident  37.804809 -122.406796
9978  Medical Incident  37.719868 -122.390905
9979  Medical Incident  37.781168 -122.434806
9981  Medical Incident  37.782444 -122.420575
9983  Medical Incident  37.797298 -122.433847
9984  Medical Incident  37.776097 -122.408564
9985  Medical Incident  37.750118 -122.390433
9986  Medical Incident  37.760638 -122.425844
9987  Medical Incident  37.779956 -122.466427
9988  Medical Incident  37.768154 -122.454312
9989  Medical Incident  37.791835 -122.410818
9991  Medical Incident  37.775885 -122.430365
9993  Medical Incident  37.761514 -122.425556
9994  Medical Incident  37.749102 -122.486927
9995  Medical Incident  37.757970 -122.416727
9996  Medical Incident  37.787082 -122.425868
9997  Medical Incident  37.784206 -122.407613
9999  Medical Incident  37.785582 -122.414617

[6791 rows x 3 columns]

In [46]:
b = mapData[mapData.call_type == 'Alarms']

In [47]:
c = mapData[mapData.call_type == 'Structure Fire']

In [48]:
c

           call_type   latitude   longitude
6     Structure Fire  37.783359 -122.416695
15    Structure Fire  37.785217 -122.417070
19    Structure Fire  37.783359 -122.416695
32    Structure Fire  37.770259 -122.431832
51    Structure Fire  37.798603 -122.423149
58    Structure Fire  37.798603 -122.423149
72    Structure Fire  37.774284 -122.467088
75    Structure Fire  37.770259 -122.431832
78    Structure Fire  37.770259 -122.431832
100   Structure Fire  37.790495 -122.402353
104   Structure Fire  37.774284 -122.467088
108   Structure Fire  37.798603 -122.423149
152   Structure Fire  37.798603 -122.423149
171   Structure Fire  37.807690 -122.412330
174   Structure Fire  37.786410 -122.408036
177   Structure Fire  37.755998 -122.409433
186   Structure Fire  37.783359 -122.416695
202   Structure Fire  37.790495 -122.402353
208   Structure Fire  37.755998 -122.409433
226   Structure Fire  37.770259 -122.431832
233   Structure Fire  37.807690 -122.412330
252   Structure Fire  37.807690 -122.412330
260   Structure Fire  37.785217 -122.417070
262   Structure Fire  37.774284 -122.467088
267   Structure Fire  37.783359 -122.416695
289   Structure Fire  37.798603 -122.423149
292   Structure Fire  37.785217 -122.417070
293   Structure Fire  37.790495 -122.402353
298   Structure Fire  37.716460 -122.441020
313   Structure Fire  37.785217 -122.417070
...              ...        ...         ...
9702  Structure Fire  37.786060 -122.414644
9724  Structure Fire  37.786268 -122.412997
9725  Structure Fire  37.786060 -122.414644
9733  Structure Fire  37.712196 -122.420839
9743  Structure Fire  37.766134 -122.421935
9752  Structure Fire  37.766134 -122.421935
9753  Structure Fire  37.786268 -122.412997
9761  Structure Fire  37.778251 -122.419883
9779  Structure Fire  37.765051 -122.419669
9791  Structure Fire  37.766134 -122.421935
9794  Structure Fire  37.733118 -122.457641
9808  Structure Fire  37.766134 -122.421935
9811  Structure Fire  37.786060 -122.414644
9823  Structure Fire  37.765051 -122.419669
9830  Structure Fire  37.726926 -122.430965
9832  Structure Fire  37.733118 -122.457641
9847  Structure Fire  37.769798 -122.448579
9880  Structure Fire  37.733118 -122.457641
9884  Structure Fire  37.769798 -122.448579
9885  Structure Fire  37.712196 -122.420839
9900  Structure Fire  37.786060 -122.414644
9924  Structure Fire  37.733118 -122.457641
9941  Structure Fire  37.712196 -122.420839
9943  Structure Fire  37.786268 -122.412997
9951  Structure Fire  37.786268 -122.412997
9960  Structure Fire  37.733118 -122.457641
9964  Structure Fire  37.786268 -122.412997
9966  Structure Fire  37.776464 -122.426263
9967  Structure Fire  37.766134 -122.421935
9980  Structure Fire  37.766134 -122.421935

[1029 rows x 3 columns]

In [51]:
a.to_csv('Medical.csv')
b.to_csv('Alarms.csv')
c.to_csv('Fire.csv')